// ═══════════════════════════════════════════════
//  KIYO'S MIND — data.js  v3
// ═══════════════════════════════════════════════

const verbData = [
  { k:"開く",       f:"あく",          m:"Abrirse (intrans.)",          g:1, lv:"N4" },
  { k:"開ける",     f:"あける",        m:"Abrir (trans.)",              g:2, lv:"N4" },
  { k:"集まる",     f:"あつまる",      m:"Reunirse",                    g:1, lv:"N4" },
  { k:"集める",     f:"あつめる",      m:"Reunir",                      g:2, lv:"N4" },
  { k:"謝る",       f:"あやまる",      m:"Disculparse",                 g:1, lv:"N4" },
  { k:"生きる",     f:"いきる",        m:"Vivir",                       g:2, lv:"N4" },
  { k:"急ぐ",       f:"いそぐ",        m:"Apresurarse",                 g:1, lv:"N4" },
  { k:"祈る",       f:"いのる",        m:"Rezar",                       g:1, lv:"N4" },
  { k:"植える",     f:"うえる",        m:"Plantar",                     g:2, lv:"N4" },
  { k:"受ける",     f:"うける",        m:"Recibir / Tomar (examen)",    g:2, lv:"N4" },
  { k:"動く",       f:"うごく",        m:"Moverse",                     g:1, lv:"N4" },
  { k:"打つ",       f:"うつ",          m:"Golpear / Teclear",           g:1, lv:"N4" },
  { k:"写す",       f:"うつす",        m:"Copiar / Fotografiar",        g:1, lv:"N4" },
  { k:"選ぶ",       f:"えらぶ",        m:"Elegir",                      g:1, lv:"N4" },
  { k:"起きる",     f:"おきる",        m:"Despertarse / Ocurrir",       g:2, lv:"N4" },
  { k:"送る",       f:"おくる",        m:"Enviar / Acompañar",          g:1, lv:"N4" },
  { k:"怒る",       f:"おこる",        m:"Enojarse",                    g:1, lv:"N4" },
  { k:"落ちる",     f:"おちる",        m:"Caer",                        g:2, lv:"N4" },
  { k:"落とす",     f:"おとす",        m:"Dejar caer",                  g:1, lv:"N4" },
  { k:"踊る",       f:"おどる",        m:"Bailar",                      g:1, lv:"N4" },
  { k:"驚く",       f:"おどろく",      m:"Sorprenderse",                g:1, lv:"N4" },
  { k:"思い出す",   f:"おもいだす",    m:"Recordar",                    g:1, lv:"N4" },
  { k:"思う",       f:"おもう",        m:"Pensar / Creer",              g:1, lv:"N4" },
  { k:"折る",       f:"おる",          m:"Doblar / Romper",             g:1, lv:"N4" },
  { k:"下りる",     f:"おりる",        m:"Bajar (de un lugar)",         g:2, lv:"N4" },
  { k:"降る",       f:"ふる",          m:"Llover / Nevar",              g:1, lv:"N4" },
  { k:"片付ける",   f:"かたづける",    m:"Ordenar / Limpiar",           g:2, lv:"N4" },
  { k:"勝つ",       f:"かつ",          m:"Ganar",                       g:1, lv:"N4" },
  { k:"変える",     f:"かえる",        m:"Cambiar algo",                g:2, lv:"N4" },
  { k:"変わる",     f:"かわる",        m:"Cambiar (intrans.)",          g:1, lv:"N4" },
  { k:"通う",       f:"かよう",        m:"Frecuentar / Ir y venir",     g:1, lv:"N4" },
  { k:"乾く",       f:"かわく",        m:"Secarse",                     g:1, lv:"N4" },
  { k:"考える",     f:"かんがえる",    m:"Pensar / Considerar",         g:2, lv:"N4" },
  { k:"頑張る",     f:"がんばる",      m:"Esforzarse",                  g:1, lv:"N4" },
  { k:"聞く",       f:"きく",          m:"Escuchar / Preguntar",        g:1, lv:"N4" },
  { k:"決まる",     f:"きまる",        m:"Decidirse",                   g:1, lv:"N4" },
  { k:"決める",     f:"きめる",        m:"Decidir",                     g:2, lv:"N4" },
  { k:"切る",       f:"きる",          m:"Cortar",                      g:1, lv:"N4" },
  { k:"着る",       f:"きる",          m:"Vestirse (torso)",            g:2, lv:"N4" },
  { k:"比べる",     f:"くらべる",      m:"Comparar",                    g:2, lv:"N4" },
  { k:"暮らす",     f:"くらす",        m:"Vivir / Pasar el tiempo",     g:1, lv:"N4" },
  { k:"消える",     f:"きえる",        m:"Apagarse / Desaparecer",      g:2, lv:"N4" },
  { k:"消す",       f:"けす",          m:"Apagar / Borrar",             g:1, lv:"N4" },
  { k:"答える",     f:"こたえる",      m:"Responder",                   g:2, lv:"N4" },
  { k:"困る",       f:"こまる",        m:"Estar en apuros",             g:1, lv:"N4" },
  { k:"壊れる",     f:"こわれる",      m:"Romperse",                    g:2, lv:"N4" },
  { k:"壊す",       f:"こわす",        m:"Romper algo",                 g:1, lv:"N4" },
  { k:"探す",       f:"さがす",        m:"Buscar",                      g:1, lv:"N4" },
  { k:"下がる",     f:"さがる",        m:"Bajar / Retroceder",          g:1, lv:"N4" },
  { k:"下げる",     f:"さげる",        m:"Bajar algo",                  g:2, lv:"N4" },
  { k:"触る",       f:"さわる",        m:"Tocar",                       g:1, lv:"N4" },
  { k:"叱る",       f:"しかる",        m:"Regañar",                     g:1, lv:"N4" },
  { k:"調べる",     f:"しらべる",      m:"Investigar / Revisar",        g:2, lv:"N4" },
  { k:"信じる",     f:"しんじる",      m:"Creer / Confiar",             g:2, lv:"N4" },
  { k:"進む",       f:"すすむ",        m:"Avanzar / Progresar",         g:1, lv:"N4" },
  { k:"捨てる",     f:"すてる",        m:"Tirar / Desechar",            g:2, lv:"N4" },
  { k:"座る",       f:"すわる",        m:"Sentarse",                    g:1, lv:"N4" },
  { k:"育つ",       f:"そだつ",        m:"Crecer / Criarse",            g:1, lv:"N4" },
  { k:"育てる",     f:"そだてる",      m:"Criar / Educar",              g:2, lv:"N4" },
  { k:"倒れる",     f:"たおれる",      m:"Caerse / Desmayarse",         g:2, lv:"N4" },
  { k:"出す",       f:"だす",          m:"Sacar / Enviar",              g:1, lv:"N4" },
  { k:"訪ねる",     f:"たずねる",      m:"Visitar / Preguntar",         g:2, lv:"N4" },
  { k:"建てる",     f:"たてる",        m:"Construir",                   g:2, lv:"N4" },
  { k:"足りる",     f:"たりる",        m:"Ser suficiente",              g:2, lv:"N4" },
  { k:"食べる",     f:"たべる",        m:"Comer",                       g:2, lv:"N4" },
  { k:"試す",       f:"ためす",        m:"Probar / Intentar",           g:1, lv:"N4" },
  { k:"楽しむ",     f:"たのしむ",      m:"Disfrutar",                   g:1, lv:"N4" },
  { k:"頼む",       f:"たのむ",        m:"Pedir / Solicitar",           g:1, lv:"N4" },
  { k:"違う",       f:"ちがう",        m:"Ser diferente / Equivocarse", g:1, lv:"N4" },
  { k:"使う",       f:"つかう",        m:"Usar",                        g:1, lv:"N4" },
  { k:"疲れる",     f:"つかれる",      m:"Cansarse",                    g:2, lv:"N4" },
  { k:"着く",       f:"つく",          m:"Llegar",                      g:1, lv:"N4" },
  { k:"付ける",     f:"つける",        m:"Encender / Pegar",            g:2, lv:"N4" },
  { k:"伝える",     f:"つたえる",      m:"Comunicar / Transmitir",      g:2, lv:"N4" },
  { k:"続く",       f:"つづく",        m:"Continuar (intrans.)",        g:1, lv:"N4" },
  { k:"続ける",     f:"つづける",      m:"Continuar algo (trans.)",     g:2, lv:"N4" },
  { k:"手伝う",     f:"てつだう",      m:"Ayudar",                      g:1, lv:"N4" },
  { k:"出掛ける",   f:"でかける",      m:"Salir (de casa)",             g:2, lv:"N4" },
  { k:"通る",       f:"とおる",        m:"Pasar por / Atravesar",       g:1, lv:"N4" },
  { k:"届く",       f:"とどく",        m:"Llegar / Alcanzar",           g:1, lv:"N4" },
  { k:"届ける",     f:"とどける",      m:"Entregar / Notificar",        g:2, lv:"N4" },
  { k:"泊まる",     f:"とまる",        m:"Hospedarse",                  g:1, lv:"N4" },
  { k:"止まる",     f:"とまる",        m:"Detenerse",                   g:1, lv:"N4" },
  { k:"止める",     f:"とめる",        m:"Detener algo",                g:2, lv:"N4" },
  { k:"取る",       f:"とる",          m:"Tomar / Coger",               g:1, lv:"N4" },
  { k:"撮る",       f:"とる",          m:"Tomar (fotos)",               g:1, lv:"N4" },
  { k:"直す",       f:"なおす",        m:"Arreglar / Reparar",          g:1, lv:"N4" },
  { k:"直る",       f:"なおる",        m:"Arreglarse / Repararse",      g:1, lv:"N4" },
  { k:"亡くなる",   f:"なくなる",      m:"Fallecer",                    g:1, lv:"N4" },
  { k:"無くす",     f:"なくす",        m:"Perder algo",                 g:1, lv:"N4" },
  { k:"投げる",     f:"なげる",        m:"Lanzar / Tirar",              g:2, lv:"N4" },
  { k:"慣れる",     f:"なれる",        m:"Acostumbrarse",               g:2, lv:"N4" },
  { k:"並ぶ",       f:"ならぶ",        m:"Hacer fila / Alinearse",      g:1, lv:"N4" },
  { k:"並べる",     f:"ならべる",      m:"Alinear / Poner en fila",     g:2, lv:"N4" },
  { k:"なる",       f:"なる",          m:"Convertirse / Llegar a ser",  g:1, lv:"N4" },
  { k:"脱ぐ",       f:"ぬぐ",          m:"Quitarse (ropa)",             g:1, lv:"N4" },
  { k:"塗る",       f:"ぬる",          m:"Pintar / Untar",              g:1, lv:"N4" },
  { k:"濡れる",     f:"ぬれる",        m:"Mojarse",                     g:2, lv:"N4" },
  { k:"寝る",       f:"ねる",          m:"Dormir / Acostarse",          g:2, lv:"N4" },
  { k:"登る",       f:"のぼる",        m:"Escalar / Subir",             g:1, lv:"N4" },
  { k:"残る",       f:"のこる",        m:"Quedar / Sobrar",             g:1, lv:"N4" },
  { k:"乗る",       f:"のる",          m:"Subir a un transporte",       g:1, lv:"N4" },
  { k:"運ぶ",       f:"はこぶ",        m:"Transportar / Cargar",        g:1, lv:"N4" },
  { k:"始まる",     f:"はじまる",      m:"Empezar (intrans.)",          g:1, lv:"N4" },
  { k:"始める",     f:"はじめる",      m:"Empezar algo (trans.)",       g:2, lv:"N4" },
  { k:"働く",       f:"はたらく",      m:"Trabajar",                    g:1, lv:"N4" },
  { k:"払う",       f:"はらう",        m:"Pagar",                       g:1, lv:"N4" },
  { k:"晴れる",     f:"はれる",        m:"Despejarse (clima)",          g:2, lv:"N4" },
  { k:"冷える",     f:"ひえる",        m:"Enfriarse",                   g:2, lv:"N4" },
  { k:"引く",       f:"ひく",          m:"Tirar / Jalar",               g:1, lv:"N4" },
  { k:"引っ越す",   f:"ひっこす",      m:"Mudarse",                     g:1, lv:"N4" },
  { k:"拾う",       f:"ひろう",        m:"Recoger / Encontrar",         g:1, lv:"N4" },
  { k:"増える",     f:"ふえる",        m:"Aumentar (intrans.)",         g:2, lv:"N4" },
  { k:"増やす",     f:"ふやす",        m:"Aumentar algo (trans.)",      g:1, lv:"N4" },
  { k:"太る",       f:"ふとる",        m:"Engordar",                    g:1, lv:"N4" },
  { k:"褒める",     f:"ほめる",        m:"Alabar / Elogiar",            g:2, lv:"N4" },
  { k:"負ける",     f:"まける",        m:"Perder (juego/batalla)",      g:2, lv:"N4" },
  { k:"間違える",   f:"まちがえる",    m:"Equivocarse",                 g:2, lv:"N4" },
  { k:"間に合う",   f:"まにあう",      m:"Llegar a tiempo",             g:1, lv:"N4" },
  { k:"守る",       f:"まもる",        m:"Proteger / Cumplir",          g:1, lv:"N4" },
  { k:"迷う",       f:"まよう",        m:"Perderse / Estar indeciso",   g:1, lv:"N4" },
  { k:"見つける",   f:"みつける",      m:"Encontrar",                   g:2, lv:"N4" },
  { k:"見せる",     f:"みせる",        m:"Mostrar",                     g:2, lv:"N4" },
  { k:"見る",       f:"みる",          m:"Ver / Mirar",                 g:2, lv:"N4" },
  { k:"向かう",     f:"むかう",        m:"Dirigirse a",                 g:1, lv:"N4" },
  { k:"迎える",     f:"むかえる",      m:"Recibir / Ir a buscar",       g:2, lv:"N4" },
  { k:"戻る",       f:"もどる",        m:"Regresar / Volver",           g:1, lv:"N4" },
  { k:"戻す",       f:"もどす",        m:"Devolver algo",               g:1, lv:"N4" },
  { k:"貰う",       f:"もらう",        m:"Recibir",                     g:1, lv:"N4" },
  { k:"焼く",       f:"やく",          m:"Asar / Hornear",              g:1, lv:"N4" },
  { k:"痩せる",     f:"やせる",        m:"Adelgazar",                   g:2, lv:"N4" },
  { k:"止める",     f:"やめる",        m:"Dejar / Renunciar",           g:2, lv:"N4" },
  { k:"汚れる",     f:"よごれる",      m:"Ensuciarse",                  g:2, lv:"N4" },
  { k:"汚す",       f:"よごす",        m:"Ensuciar algo",               g:1, lv:"N4" },
  { k:"寄る",       f:"よる",          m:"Acercarse / Pasar por",       g:1, lv:"N4" },
  { k:"喜ぶ",       f:"よろこぶ",      m:"Alegrarse",                   g:1, lv:"N4" },
  { k:"分かる",     f:"わかる",        m:"Entender",                    g:1, lv:"N4" },
  { k:"別れる",     f:"わかれる",      m:"Separarse / Dividirse",       g:2, lv:"N4" },
  { k:"忘れる",     f:"わすれる",      m:"Olvidar",                     g:2, lv:"N4" },
  { k:"笑う",       f:"わらう",        m:"Reír",                        g:1, lv:"N4" },
  // suru
  { k:"安心する",   f:"あんしんする",  m:"Tranquilizarse",              g:3, lv:"N4" },
  { k:"案内する",   f:"あんないする",  m:"Guiar / Mostrar el camino",   g:3, lv:"N4" },
  { k:"運転する",   f:"うんてんする",  m:"Conducir",                    g:3, lv:"N4" },
  { k:"運動する",   f:"うんどうする",  m:"Hacer ejercicio",             g:3, lv:"N4" },
  { k:"感謝する",   f:"かんしゃする",  m:"Agradecer",                   g:3, lv:"N4" },
  { k:"故障する",   f:"こしょうする",  m:"Averiarse",                   g:3, lv:"N4" },
  { k:"紹介する",   f:"しょうかいする",m:"Presentar a alguien",         g:3, lv:"N4" },
  { k:"招待する",   f:"しょうたいする",m:"Invitar",                     g:3, lv:"N4" },
  { k:"食事する",   f:"しょくじする",  m:"Comer / Almorzar",            g:3, lv:"N4" },
  { k:"心配する",   f:"しんぱいする",  m:"Preocuparse",                 g:3, lv:"N4" },
  { k:"説明する",   f:"せつめいする",  m:"Explicar",                    g:3, lv:"N4" },
  { k:"失敗する",   f:"しっぱいする",  m:"Fracasar / Fallar",           g:3, lv:"N4" },
  { k:"相談する",   f:"そうだんする",  m:"Consultar",                   g:3, lv:"N4" },
  { k:"注意する",   f:"ちゅういする",  m:"Tener cuidado / Advertir",    g:3, lv:"N4" },
  { k:"注文する",   f:"ちゅうもんする",m:"Pedir / Hacer un pedido",     g:3, lv:"N4" },
  { k:"遅刻する",   f:"ちこくする",    m:"Llegar tarde",                g:3, lv:"N4" },
  { k:"貯金する",   f:"ちょきんする",  m:"Ahorrar dinero",              g:3, lv:"N4" },
  { k:"用意する",   f:"よういする",    m:"Preparar",                    g:3, lv:"N4" },
  { k:"予約する",   f:"よやくする",    m:"Reservar",                    g:3, lv:"N4" },
  { k:"約束する",   f:"やくそくする",  m:"Prometer",                    g:3, lv:"N4" },
  { k:"練習する",   f:"れんしゅうする",m:"Practicar",                   g:3, lv:"N4" },
  { k:"連絡する",   f:"れんらくする",  m:"Contactar",                   g:3, lv:"N4" },
  { k:"留学する",   f:"りゅうがくする",m:"Estudiar en el extranjero",   g:3, lv:"N4" },
  { k:"合格する",   f:"ごうかくする",  m:"Aprobar (un examen)",         g:3, lv:"N4" },
  { k:"復習する",   f:"ふくしゅうする",m:"Repasar",                     g:3, lv:"N4" },
  { k:"経験する",   f:"けいけんする",  m:"Experimentar",                g:3, lv:"N4" },
  { k:"計画する",   f:"けいかくする",  m:"Planear",                     g:3, lv:"N4" },
  { k:"喧嘩する",   f:"けんかする",    m:"Pelear / Discutir",           g:3, lv:"N4" },
  { k:"散歩する",   f:"さんぽする",    m:"Pasear",                      g:3, lv:"N4" },
  { k:"出席する",   f:"しゅっせきする",m:"Asistir",                     g:3, lv:"N4" },
  { k:"出発する",   f:"しゅっぱつする",m:"Partir / Salir (viaje)",      g:3, lv:"N4" },
  { k:"準備する",   f:"じゅんびする",  m:"Preparar",                    g:3, lv:"N4" },
  { k:"質問する",   f:"しつもんする",  m:"Preguntar",                   g:3, lv:"N4" },
  { k:"掃除する",   f:"そうじする",    m:"Limpiar",                     g:3, lv:"N4" },
  { k:"洗濯する",   f:"せんたくする",  m:"Lavar la ropa",               g:3, lv:"N4" },
  { k:"到着する",   f:"とうちゃくする",m:"Llegar",                      g:3, lv:"N4" },
  { k:"返事する",   f:"へんじする",    m:"Responder / Contestar",       g:3, lv:"N4" },
  { k:"くる",       f:"くる",          m:"Venir",                       g:3, lv:"N4" },
  { k:"する",       f:"する",          m:"Hacer",                       g:3, lv:"N4" },
];

const grammarData = [
  { f:"nai_stem", tag:"〜なければなりません",     m:"Tener que (obligación)",          lv:"N4", formula:"V-ない(raíz) + ければなりません", hint:"食べる → 食べ + なければなりません" },
  { f:"nai_stem", tag:"〜なくてもいいです",        m:"No es necesario",                 lv:"N4", formula:"V-ない(raíz) + くてもいいです",  hint:"食べる → 食べ + なくてもいいです" },
  { f:"te",       tag:"〜てはいけません",          m:"Prohibido / No se permite",       lv:"N4", formula:"V-て + はいけません",             hint:"話す → 話して + はいけません" },
  { f:"te",       tag:"〜てもいいです",            m:"Se permite / Está bien que...",   lv:"N4", formula:"V-て + もいいです",               hint:"食べる → 食べて + もいいです" },
  { f:"te",       tag:"〜ています",               m:"Estar haciendo / Estado result.", lv:"N4", formula:"V-て + います",                  hint:"食べる → 食べています" },
  { f:"te",       tag:"〜てあります",             m:"Algo está hecho con intención",   lv:"N4", formula:"V-て + あります",                hint:"書く → 書いてあります" },
  { f:"te",       tag:"〜ておきます",             m:"Hacer algo con antelación",        lv:"N4", formula:"V-て + おきます",                hint:"買う → 買っておきます" },
  { f:"te",       tag:"〜てしまいます",           m:"Hacer completamente / lament.",   lv:"N4", formula:"V-て + しまいます",              hint:"食べる → 食べてしまいました" },
  { f:"te",       tag:"〜てくる",                m:"Acción que se acerca al presente", lv:"N4", formula:"V-て + くる",                    hint:"増える → 増えてきた" },
  { f:"te",       tag:"〜ていく",                m:"Acción que se aleja al futuro",    lv:"N4", formula:"V-て + いく",                    hint:"減る → 減っていく" },
  { f:"ta",       tag:"〜たことがあります",       m:"Haber tenido la experiencia de",  lv:"N4", formula:"V-た + ことがあります",           hint:"行く → 行ったことがあります" },
  { f:"te",       tag:"〜てみます",              m:"Intentar hacer algo",              lv:"N4", formula:"V-て + みます",                  hint:"食べる → 食べてみます" },
  { f:"ta",       tag:"〜たほうがいいです",       m:"Es mejor que... (consejo)",       lv:"N4", formula:"V-た + ほうがいいです",           hint:"寝る → 寝たほうがいいです" },
  { f:"nai_stem", tag:"〜ないほうがいいです",     m:"Es mejor que no...",              lv:"N4", formula:"V-ない(raíz) + ないほうがいいです", hint:"食べる → 食べないほうがいいです" },
  { f:"masu",     tag:"〜たいです",              m:"Querer hacer algo",                lv:"N4", formula:"V-ます(raíz) + たいです",        hint:"行く → 行き + たいです" },
  { f:"Volitivo", tag:"〜（よ）うと思っています", m:"Estoy pensando en...",            lv:"N4", formula:"V-volitivo + と思っています",    hint:"受ける → 受けようと思っています" },
  { f:"Potencial", tag:"〜（られ）る (Potencial)", m:"Poder hacer algo",              lv:"N4", formula:"V-potencial",                    hint:"食べる → 食べられる, 書く → 書ける" },
  { f:"ta",       tag:"〜たら",                 m:"Si / Cuando algo ocurre",          lv:"N4", formula:"V-た + ら",                      hint:"帰る → 帰ったら、電話します" },
  { f:"te",       tag:"〜てあげる",             m:"Hacer un favor a alguien",         lv:"N4", formula:"V-て + あげる",                  hint:"教える → 教えてあげる" },
  { f:"te",       tag:"〜てくれる",             m:"Alguien me hace un favor",         lv:"N4", formula:"V-て + くれる",                  hint:"手伝う → 手伝ってくれた" },
  { f:"te",       tag:"〜てもらう",             m:"Recibir un favor de alguien",      lv:"N4", formula:"V-て + もらう",                  hint:"直す → 直してもらった" },
  { f:"masu",     tag:"〜に行く",              m:"Ir a hacer algo",                   lv:"N4", formula:"V-ます(raíz) + に行く",          hint:"食べる → 食べに行く" },
  { f:"ta",       tag:"〜たあとで",            m:"Después de hacer...",               lv:"N4", formula:"V-た + あとで",                  hint:"食べる → 食べたあとで" },
  { f:"te",       tag:"〜てから",              m:"Después de / Desde que hice...",    lv:"N4", formula:"V-て + から",                    hint:"食べる → 食べてから" },
  { f:"masu",     tag:"〜ながら",              m:"Mientras se hace otra cosa",        lv:"N4", formula:"V-ます(raíz) + ながら",          hint:"聞く → 聞き + ながら" },
  { f:"masu",     tag:"〜すぎる",              m:"Hacer algo en exceso",              lv:"N4", formula:"V-ます(raíz) + すぎる",          hint:"食べる → 食べ + すぎる" },
  { f:"masu",     tag:"〜やすい",              m:"Fácil de hacer",                    lv:"N4", formula:"V-ます(raíz) + やすい",          hint:"使う → 使い + やすい" },
  { f:"masu",     tag:"〜にくい",              m:"Difícil de hacer",                  lv:"N4", formula:"V-ます(raíz) + にくい",          hint:"読む → 読み + にくい" },
  { f:"masu",     tag:"〜方（かた）",           m:"Manera de hacer algo",             lv:"N4", formula:"V-ます(raíz) + 方",              hint:"食べる → 食べ + 方" },
  { f:"masu",     tag:"〜だす",               m:"Empezar a (de repente)",            lv:"N4", formula:"V-ます(raíz) + だす",            hint:"走る → 走り + だす" },
  { f:"masu",     tag:"〜おわる",             m:"Terminar de hacer",                  lv:"N4", formula:"V-ます(raíz) + おわる",          hint:"食べる → 食べ + おわる" },
  { f:"dic",      tag:"〜ようになる",          m:"Llegar a ser capaz de",             lv:"N4", formula:"V-dic + ようになる",             hint:"話せる + ようになった" },
  { f:"dic",      tag:"〜ようにする",          m:"Intentar / Asegurarse de hacer",    lv:"N4", formula:"V-dic + ようにする",             hint:"食べる + ようにする" },
  { f:"Pasiva",   tag:"〜られる (Pasiva)",     m:"Ser hecho por alguien",            lv:"N4", formula:"V-pasivo",                       hint:"叱る → 叱られる" },
  { f:"ta",       tag:"〜たばかり",            m:"Acabar de hacer algo",              lv:"N4", formula:"V-た + ばかり",                  hint:"食べる → 食べたばかりです" },
];

// ═══════════════════════════════════════════════
//  STAR DATA — Formato JLPT real
//  parts: array de 4 strings (opciones 1-4)
//  sentence: oración con [1][2][★][3] = blanks
//  starIndex: cuál de los 4 va en la posición ★ (1-based)
//  correct: texto exacto de la respuesta correcta
//  translation: significado de la oración completa
// ═══════════════════════════════════════════════
const starData = [
  {
    lv:"N4",
    grammar:"〜なければなりません",
    sentence:"毎日　＿＿　＿＿　★　＿＿。",
    parts:["薬を","飲ま","なければ","なりません"],
    starIndex:3,
    correct:"なければ",
    translation:"Todos los días tengo que tomar la medicina."
  },
  {
    lv:"N4",
    grammar:"〜たことがあります",
    sentence:"私は　＿＿　＿＿　★　＿＿。",
    parts:["富士山に","登った","こと","があります"],
    starIndex:3,
    correct:"こと",
    translation:"He subido al Monte Fuji alguna vez."
  },
  {
    lv:"N4",
    grammar:"〜てもいいです",
    sentence:"ここで　＿＿　＿＿　★　＿＿か？",
    parts:["写真を","撮っ","ても","いいです"],
    starIndex:3,
    correct:"ても",
    translation:"¿Está bien tomar fotos aquí?"
  },
  {
    lv:"N4",
    grammar:"〜てはいけません",
    sentence:"図書館で　＿＿　＿＿　★　＿＿。",
    parts:["大きな","声で","話し","てはいけません"],
    starIndex:3,
    correct:"話し",
    translation:"No se permite hablar en voz alta en la biblioteca."
  },
  {
    lv:"N4",
    grammar:"〜ようになりました",
    sentence:"練習して　＿＿　＿＿　★　＿＿。",
    parts:["漢字が","読める","よう","になりました"],
    starIndex:3,
    correct:"よう",
    translation:"Con la práctica, llegué a poder leer kanji."
  },
  {
    lv:"N4",
    grammar:"〜てから",
    sentence:"シャワーを　＿＿　＿＿　★　＿＿。",
    parts:["浴び","て","から","寝ます"],
    starIndex:3,
    correct:"から",
    translation:"Después de ducharme, me voy a dormir."
  },
  {
    lv:"N4",
    grammar:"〜たほうがいいです",
    sentence:"風邪の　＿＿　＿＿　★　＿＿。",
    parts:["とき","は","早く寝た","ほうがいいです"],
    starIndex:3,
    correct:"早く寝た",
    translation:"Cuando tienes resfriado, es mejor dormir temprano."
  },
  {
    lv:"N4",
    grammar:"〜てもらいました",
    sentence:"友達に　＿＿　＿＿　★　＿＿。",
    parts:["荷物を","持っ","て","もらいました"],
    starIndex:3,
    correct:"て",
    translation:"Le pedí a mi amigo que me cargara el equipaje."
  },
  {
    lv:"N4",
    grammar:"〜ながら",
    sentence:"音楽を　＿＿　＿＿　★　＿＿。",
    parts:["聞き","なが","ら","勉強します"],
    starIndex:2,
    correct:"なが",
    translation:"Estudio mientras escucho música."
  },
  {
    lv:"N4",
    grammar:"〜ておきます",
    sentence:"パーティーの　＿＿　＿＿　★　＿＿。",
    parts:["前に","飲み物を","買っ","ておきます"],
    starIndex:3,
    correct:"買っ",
    translation:"Antes de la fiesta, compraré bebidas de antemano."
  },
  {
    lv:"N4",
    grammar:"〜てしまいました",
    sentence:"大事な　＿＿　＿＿　★　＿＿。",
    parts:["書類を","なく","し","てしまいました"],
    starIndex:3,
    correct:"し",
    translation:"Por desgracia perdí un documento importante."
  },
  {
    lv:"N4",
    grammar:"〜たら",
    sentence:"春に　＿＿　＿＿　★　＿＿。",
    parts:["なっ","た","ら","花見をしましょう"],
    starIndex:3,
    correct:"ら",
    translation:"Cuando llegue la primavera, hagamos hanami."
  },
  {
    lv:"N4",
    grammar:"〜てくれました",
    sentence:"先生が　＿＿　＿＿　★　＿＿。",
    parts:["作文を","直し","て","くれました"],
    starIndex:3,
    correct:"て",
    translation:"El profesor me corrigió la redacción."
  },
  {
    lv:"N4",
    grammar:"〜すぎます",
    sentence:"この　＿＿　＿＿　★　＿＿。",
    parts:["バッグは","重","す","ぎます"],
    starIndex:3,
    correct:"す",
    translation:"Esta bolsa es demasiado pesada."
  },
  {
    lv:"N4",
    grammar:"〜たばかりです",
    sentence:"さっき　＿＿　＿＿　★　＿＿。",
    parts:["ご飯を","食べ","た","ばかりです"],
    starIndex:3,
    correct:"た",
    translation:"Acabo de comer hace un momento."
  },
  {
    lv:"N4",
    grammar:"〜てみます",
    sentence:"この　＿＿　＿＿　★　＿＿。",
    parts:["料理を","一度","作っ","てみます"],
    starIndex:3,
    correct:"てみます",
    translation:"Voy a intentar hacer esta comida una vez."
  },
  {
    lv:"N4",
    grammar:"〜ようにしています",
    sentence:"毎日　＿＿　＿＿　★　＿＿。",
    parts:["野菜を","食べる","よう","にしています"],
    starIndex:3,
    correct:"よう",
    translation:"Me aseguro de comer verduras todos los días."
  },
  {
    lv:"N4",
    grammar:"〜てあげました",
    sentence:"道に　＿＿　＿＿　★　＿＿。",
    parts:["迷っている","人に","教え","てあげました"],
    starIndex:3,
    correct:"教え",
    translation:"Le indiqué el camino a una persona que estaba perdida."
  },
  {
    lv:"N4",
    grammar:"〜やすいです",
    sentence:"この　＿＿　＿＿　★　＿＿。",
    parts:["アプリは","使い","やす","いです"],
    starIndex:3,
    correct:"やす",
    translation:"Esta aplicación es fácil de usar."
  },
  {
    lv:"N4",
    grammar:"〜られました（受身）",
    sentence:"授業中に　＿＿　＿＿　★　＿＿。",
    parts:["先生に","名前を","呼ば","れました"],
    starIndex:3,
    correct:"れました",
    translation:"Durante la clase, el profesor me llamó por mi nombre."
  },
];
