// ═══════════════════════════════════════════
//  KIYO'S MIND — data.js  v4
// ═══════════════════════════════════════════

const verbData = [
  // ── Grupo 1 (五段) ─────────────────────
  { k:"開く",     f:"あく",       m:"Abrirse (intrans.)",          g:1, lv:"N4" },
  { k:"集まる",   f:"あつまる",   m:"Reunirse",                    g:1, lv:"N4" },
  { k:"謝る",     f:"あやまる",   m:"Disculparse",                 g:1, lv:"N4" },
  { k:"急ぐ",     f:"いそぐ",     m:"Apresurarse",                 g:1, lv:"N4" },
  { k:"祈る",     f:"いのる",     m:"Rezar",                       g:1, lv:"N4" },
  { k:"動く",     f:"うごく",     m:"Moverse",                     g:1, lv:"N4" },
  { k:"打つ",     f:"うつ",       m:"Golpear / Teclear",           g:1, lv:"N4" },
  { k:"写す",     f:"うつす",     m:"Copiar / Fotografiar",        g:1, lv:"N4" },
  { k:"選ぶ",     f:"えらぶ",     m:"Elegir",                      g:1, lv:"N4" },
  { k:"送る",     f:"おくる",     m:"Enviar / Acompañar",          g:1, lv:"N4" },
  { k:"怒る",     f:"おこる",     m:"Enojarse",                    g:1, lv:"N4" },
  { k:"落とす",   f:"おとす",     m:"Dejar caer",                  g:1, lv:"N4" },
  { k:"踊る",     f:"おどる",     m:"Bailar",                      g:1, lv:"N4" },
  { k:"驚く",     f:"おどろく",   m:"Sorprenderse",                g:1, lv:"N4" },
  { k:"思い出す", f:"おもいだす", m:"Recordar",                    g:1, lv:"N4" },
  { k:"思う",     f:"おもう",     m:"Pensar / Creer",              g:1, lv:"N4" },
  { k:"折る",     f:"おる",       m:"Doblar / Romper",             g:1, lv:"N4" },
  { k:"降る",     f:"ふる",       m:"Llover / Nevar",              g:1, lv:"N4" },
  { k:"勝つ",     f:"かつ",       m:"Ganar",                       g:1, lv:"N4" },
  { k:"変わる",   f:"かわる",     m:"Cambiar (intrans.)",          g:1, lv:"N4" },
  { k:"通う",     f:"かよう",     m:"Frecuentar",                  g:1, lv:"N4" },
  { k:"乾く",     f:"かわく",     m:"Secarse",                     g:1, lv:"N4" },
  { k:"頑張る",   f:"がんばる",   m:"Esforzarse",                  g:1, lv:"N4" },
  { k:"聞く",     f:"きく",       m:"Escuchar / Preguntar",        g:1, lv:"N4" },
  { k:"切る",     f:"きる",       m:"Cortar",                      g:1, lv:"N4" },
  { k:"決まる",   f:"きまる",     m:"Decidirse",                   g:1, lv:"N4" },
  { k:"暮らす",   f:"くらす",     m:"Vivir / Pasar el tiempo",     g:1, lv:"N4" },
  { k:"消す",     f:"けす",       m:"Apagar / Borrar",             g:1, lv:"N4" },
  { k:"困る",     f:"こまる",     m:"Estar en apuros",             g:1, lv:"N4" },
  { k:"壊す",     f:"こわす",     m:"Romper algo",                 g:1, lv:"N4" },
  { k:"探す",     f:"さがす",     m:"Buscar",                      g:1, lv:"N4" },
  { k:"下がる",   f:"さがる",     m:"Bajar / Retroceder",          g:1, lv:"N4" },
  { k:"触る",     f:"さわる",     m:"Tocar",                       g:1, lv:"N4" },
  { k:"叱る",     f:"しかる",     m:"Regañar",                     g:1, lv:"N4" },
  { k:"進む",     f:"すすむ",     m:"Avanzar / Progresar",         g:1, lv:"N4" },
  { k:"座る",     f:"すわる",     m:"Sentarse",                    g:1, lv:"N4" },
  { k:"育つ",     f:"そだつ",     m:"Crecer / Criarse",            g:1, lv:"N4" },
  { k:"出す",     f:"だす",       m:"Sacar / Enviar",              g:1, lv:"N4" },
  { k:"試す",     f:"ためす",     m:"Probar / Intentar",           g:1, lv:"N4" },
  { k:"楽しむ",   f:"たのしむ",   m:"Disfrutar",                   g:1, lv:"N4" },
  { k:"頼む",     f:"たのむ",     m:"Pedir / Solicitar",           g:1, lv:"N4" },
  { k:"違う",     f:"ちがう",     m:"Ser diferente",               g:1, lv:"N4" },
  { k:"使う",     f:"つかう",     m:"Usar",                        g:1, lv:"N4" },
  { k:"着く",     f:"つく",       m:"Llegar",                      g:1, lv:"N4" },
  { k:"続く",     f:"つづく",     m:"Continuar (intrans.)",        g:1, lv:"N4" },
  { k:"包む",     f:"つつむ",     m:"Envolver",                    g:1, lv:"N4" },
  { k:"手伝う",   f:"てつだう",   m:"Ayudar",                      g:1, lv:"N4" },
  { k:"通る",     f:"とおる",     m:"Pasar por / Atravesar",       g:1, lv:"N4" },
  { k:"届く",     f:"とどく",     m:"Llegar / Alcanzar",           g:1, lv:"N4" },
  { k:"泊まる",   f:"とまる",     m:"Hospedarse",                  g:1, lv:"N4" },
  { k:"止まる",   f:"とまる",     m:"Detenerse",                   g:1, lv:"N4" },
  { k:"取る",     f:"とる",       m:"Tomar / Coger",               g:1, lv:"N4" },
  { k:"撮る",     f:"とる",       m:"Tomar (fotos)",               g:1, lv:"N4" },
  { k:"直す",     f:"なおす",     m:"Arreglar / Reparar",          g:1, lv:"N4" },
  { k:"直る",     f:"なおる",     m:"Arreglarse (intrans.)",       g:1, lv:"N4" },
  { k:"亡くなる", f:"なくなる",   m:"Fallecer",                    g:1, lv:"N4" },
  { k:"無くす",   f:"なくす",     m:"Perder algo",                 g:1, lv:"N4" },
  { k:"並ぶ",     f:"ならぶ",     m:"Hacer fila / Alinearse",      g:1, lv:"N4" },
  { k:"なる",     f:"なる",       m:"Convertirse / Llegar a ser",  g:1, lv:"N4" },
  { k:"脱ぐ",     f:"ぬぐ",       m:"Quitarse (ropa)",             g:1, lv:"N4" },
  { k:"塗る",     f:"ぬる",       m:"Pintar / Untar",              g:1, lv:"N4" },
  { k:"登る",     f:"のぼる",     m:"Escalar / Subir",             g:1, lv:"N4" },
  { k:"残る",     f:"のこる",     m:"Quedar / Sobrar",             g:1, lv:"N4" },
  { k:"乗る",     f:"のる",       m:"Subir a un transporte",       g:1, lv:"N4" },
  { k:"運ぶ",     f:"はこぶ",     m:"Transportar / Cargar",        g:1, lv:"N4" },
  { k:"始まる",   f:"はじまる",   m:"Empezar (intrans.)",          g:1, lv:"N4" },
  { k:"働く",     f:"はたらく",   m:"Trabajar",                    g:1, lv:"N4" },
  { k:"払う",     f:"はらう",     m:"Pagar",                       g:1, lv:"N4" },
  { k:"引く",     f:"ひく",       m:"Tirar / Jalar",               g:1, lv:"N4" },
  { k:"引っ越す", f:"ひっこす",   m:"Mudarse",                     g:1, lv:"N4" },
  { k:"拾う",     f:"ひろう",     m:"Recoger / Encontrar",         g:1, lv:"N4" },
  { k:"増やす",   f:"ふやす",     m:"Aumentar algo (trans.)",      g:1, lv:"N4" },
  { k:"太る",     f:"ふとる",     m:"Engordar",                    g:1, lv:"N4" },
  { k:"踏む",     f:"ふむ",       m:"Pisar",                       g:1, lv:"N4" },
  { k:"負ける",   f:"まける",     m:"Perder (juego/batalla)",      g:1, lv:"N4" },
  { k:"間に合う", f:"まにあう",   m:"Llegar a tiempo",             g:1, lv:"N4" },
  { k:"守る",     f:"まもる",     m:"Proteger / Cumplir",          g:1, lv:"N4" },
  { k:"迷う",     f:"まよう",     m:"Perderse / Estar indeciso",   g:1, lv:"N4" },
  { k:"向かう",   f:"むかう",     m:"Dirigirse a",                 g:1, lv:"N4" },
  { k:"戻る",     f:"もどる",     m:"Regresar / Volver",           g:1, lv:"N4" },
  { k:"戻す",     f:"もどす",     m:"Devolver algo",               g:1, lv:"N4" },
  { k:"貰う",     f:"もらう",     m:"Recibir",                     g:1, lv:"N4" },
  { k:"焼く",     f:"やく",       m:"Asar / Hornear",              g:1, lv:"N4" },
  { k:"汚す",     f:"よごす",     m:"Ensuciar algo",               g:1, lv:"N4" },
  { k:"寄る",     f:"よる",       m:"Acercarse / Pasar por",       g:1, lv:"N4" },
  { k:"喜ぶ",     f:"よろこぶ",   m:"Alegrarse",                   g:1, lv:"N4" },
  { k:"分かる",   f:"わかる",     m:"Entender",                    g:1, lv:"N4" },
  { k:"笑う",     f:"わらう",     m:"Reír",                        g:1, lv:"N4" },

  // ── Grupo 2 (一段) ─────────────────────
  { k:"開ける",   f:"あける",     m:"Abrir (trans.)",              g:2, lv:"N4" },
  { k:"集める",   f:"あつめる",   m:"Reunir",                      g:2, lv:"N4" },
  { k:"生きる",   f:"いきる",     m:"Vivir",                       g:2, lv:"N4" },
  { k:"植える",   f:"うえる",     m:"Plantar",                     g:2, lv:"N4" },
  { k:"受ける",   f:"うける",     m:"Recibir / Tomar (examen)",    g:2, lv:"N4" },
  { k:"起きる",   f:"おきる",     m:"Despertarse / Ocurrir",       g:2, lv:"N4" },
  { k:"落ちる",   f:"おちる",     m:"Caer",                        g:2, lv:"N4" },
  { k:"折れる",   f:"おれる",     m:"Doblarse (intrans.)",         g:2, lv:"N4" },
  { k:"下りる",   f:"おりる",     m:"Bajar (de un lugar)",         g:2, lv:"N4" },
  { k:"片付ける", f:"かたづける", m:"Ordenar / Limpiar",           g:2, lv:"N4" },
  { k:"変える",   f:"かえる",     m:"Cambiar algo",                g:2, lv:"N4" },
  { k:"考える",   f:"かんがえる", m:"Pensar / Considerar",         g:2, lv:"N4" },
  { k:"聞こえる", f:"きこえる",   m:"Oírse / Ser audible",         g:2, lv:"N4" },
  { k:"決める",   f:"きめる",     m:"Decidir",                     g:2, lv:"N4" },
  { k:"着る",     f:"きる",       m:"Vestirse (torso)",            g:2, lv:"N4" },
  { k:"比べる",   f:"くらべる",   m:"Comparar",                    g:2, lv:"N4" },
  { k:"消える",   f:"きえる",     m:"Apagarse / Desaparecer",      g:2, lv:"N4" },
  { k:"答える",   f:"こたえる",   m:"Responder",                   g:2, lv:"N4" },
  { k:"壊れる",   f:"こわれる",   m:"Romperse",                    g:2, lv:"N4" },
  { k:"下げる",   f:"さげる",     m:"Bajar algo",                  g:2, lv:"N4" },
  { k:"調べる",   f:"しらべる",   m:"Investigar / Revisar",        g:2, lv:"N4" },
  { k:"信じる",   f:"しんじる",   m:"Creer / Confiar",             g:2, lv:"N4" },
  { k:"捨てる",   f:"すてる",     m:"Tirar / Desechar",            g:2, lv:"N4" },
  { k:"育てる",   f:"そだてる",   m:"Criar / Educar",              g:2, lv:"N4" },
  { k:"倒れる",   f:"たおれる",   m:"Caerse / Desmayarse",         g:2, lv:"N4" },
  { k:"訪ねる",   f:"たずねる",   m:"Visitar / Preguntar",         g:2, lv:"N4" },
  { k:"建てる",   f:"たてる",     m:"Construir",                   g:2, lv:"N4" },
  { k:"足りる",   f:"たりる",     m:"Ser suficiente",              g:2, lv:"N4" },
  { k:"食べる",   f:"たべる",     m:"Comer",                       g:2, lv:"N4" },
  { k:"疲れる",   f:"つかれる",   m:"Cansarse",                    g:2, lv:"N4" },
  { k:"付ける",   f:"つける",     m:"Encender / Pegar",            g:2, lv:"N4" },
  { k:"伝える",   f:"つたえる",   m:"Comunicar / Transmitir",      g:2, lv:"N4" },
  { k:"続ける",   f:"つづける",   m:"Continuar algo (trans.)",     g:2, lv:"N4" },
  { k:"手伝える", f:"てつだえる", m:"Poder ayudar",                g:2, lv:"N4" },
  { k:"出掛ける", f:"でかける",   m:"Salir (de casa)",             g:2, lv:"N4" },
  { k:"届ける",   f:"とどける",   m:"Entregar / Notificar",        g:2, lv:"N4" },
  { k:"止める",   f:"とめる",     m:"Detener algo",                g:2, lv:"N4" },
  { k:"投げる",   f:"なげる",     m:"Lanzar / Tirar",              g:2, lv:"N4" },
  { k:"慣れる",   f:"なれる",     m:"Acostumbrarse",               g:2, lv:"N4" },
  { k:"並べる",   f:"ならべる",   m:"Alinear / Poner en fila",     g:2, lv:"N4" },
  { k:"濡れる",   f:"ぬれる",     m:"Mojarse",                     g:2, lv:"N4" },
  { k:"寝る",     f:"ねる",       m:"Dormir / Acostarse",          g:2, lv:"N4" },
  { k:"増える",   f:"ふえる",     m:"Aumentar (intrans.)",         g:2, lv:"N4" },
  { k:"褒める",   f:"ほめる",     m:"Alabar / Elogiar",            g:2, lv:"N4" },
  { k:"間違える", f:"まちがえる", m:"Equivocarse",                 g:2, lv:"N4" },
  { k:"見つける", f:"みつける",   m:"Encontrar",                   g:2, lv:"N4" },
  { k:"見せる",   f:"みせる",     m:"Mostrar",                     g:2, lv:"N4" },
  { k:"見る",     f:"みる",       m:"Ver / Mirar",                 g:2, lv:"N4" },
  { k:"迎える",   f:"むかえる",   m:"Recibir / Ir a buscar",       g:2, lv:"N4" },
  { k:"痩せる",   f:"やせる",     m:"Adelgazar",                   g:2, lv:"N4" },
  { k:"止める",   f:"やめる",     m:"Dejar / Renunciar",           g:2, lv:"N4" },
  { k:"汚れる",   f:"よごれる",   m:"Ensuciarse",                  g:2, lv:"N4" },
  { k:"別れる",   f:"わかれる",   m:"Separarse / Dividirse",       g:2, lv:"N4" },
  { k:"忘れる",   f:"わすれる",   m:"Olvidar",                     g:2, lv:"N4" },
  { k:"晴れる",   f:"はれる",     m:"Despejarse (clima)",          g:2, lv:"N4" },
  { k:"冷える",   f:"ひえる",     m:"Enfriarse",                   g:2, lv:"N4" },

  // ── Grupo 3 (不規則) ───────────────────
  { k:"くる",       f:"くる",          m:"Venir",                       g:3, lv:"N4" },
  { k:"する",       f:"する",          m:"Hacer",                       g:3, lv:"N4" },
  { k:"安心する",   f:"あんしんする",  m:"Tranquilizarse",              g:3, lv:"N4" },
  { k:"案内する",   f:"あんないする",  m:"Guiar / Mostrar el camino",   g:3, lv:"N4" },
  { k:"運転する",   f:"うんてんする",  m:"Conducir",                    g:3, lv:"N4" },
  { k:"運動する",   f:"うんどうする",  m:"Hacer ejercicio",             g:3, lv:"N4" },
  { k:"感謝する",   f:"かんしゃする",  m:"Agradecer",                   g:3, lv:"N4" },
  { k:"故障する",   f:"こしょうする",  m:"Averiarse",                   g:3, lv:"N4" },
  { k:"紹介する",   f:"しょうかいする",m:"Presentar a alguien",         g:3, lv:"N4" },
  { k:"招待する",   f:"しょうたいする",m:"Invitar",                     g:3, lv:"N4" },
  { k:"食事する",   f:"しょくじする",  m:"Comer / Almorzar",            g:3, lv:"N4" },
  { k:"心配する",   f:"しんぱいする",  m:"Preocuparse",                 g:3, lv:"N4" },
  { k:"説明する",   f:"せつめいする",  m:"Explicar",                    g:3, lv:"N4" },
  { k:"失敗する",   f:"しっぱいする",  m:"Fracasar / Fallar",           g:3, lv:"N4" },
  { k:"相談する",   f:"そうだんする",  m:"Consultar",                   g:3, lv:"N4" },
  { k:"注意する",   f:"ちゅういする",  m:"Tener cuidado / Advertir",    g:3, lv:"N4" },
  { k:"注文する",   f:"ちゅうもんする",m:"Pedir / Hacer un pedido",     g:3, lv:"N4" },
  { k:"遅刻する",   f:"ちこくする",    m:"Llegar tarde",                g:3, lv:"N4" },
  { k:"貯金する",   f:"ちょきんする",  m:"Ahorrar dinero",              g:3, lv:"N4" },
  { k:"用意する",   f:"よういする",    m:"Preparar",                    g:3, lv:"N4" },
  { k:"予約する",   f:"よやくする",    m:"Reservar",                    g:3, lv:"N4" },
  { k:"約束する",   f:"やくそくする",  m:"Prometer",                    g:3, lv:"N4" },
  { k:"練習する",   f:"れんしゅうする",m:"Practicar",                   g:3, lv:"N4" },
  { k:"連絡する",   f:"れんらくする",  m:"Contactar",                   g:3, lv:"N4" },
  { k:"留学する",   f:"りゅうがくする",m:"Estudiar en el extranjero",   g:3, lv:"N4" },
  { k:"合格する",   f:"ごうかくする",  m:"Aprobar (un examen)",         g:3, lv:"N4" },
  { k:"復習する",   f:"ふくしゅうする",m:"Repasar",                     g:3, lv:"N4" },
  { k:"経験する",   f:"けいけんする",  m:"Experimentar",                g:3, lv:"N4" },
  { k:"計画する",   f:"けいかくする",  m:"Planear",                     g:3, lv:"N4" },
  { k:"喧嘩する",   f:"けんかする",    m:"Pelear / Discutir",           g:3, lv:"N4" },
  { k:"散歩する",   f:"さんぽする",    m:"Pasear",                      g:3, lv:"N4" },
  { k:"出席する",   f:"しゅっせきする",m:"Asistir",                     g:3, lv:"N4" },
  { k:"出発する",   f:"しゅっぱつする",m:"Partir / Salir (viaje)",      g:3, lv:"N4" },
  { k:"準備する",   f:"じゅんびする",  m:"Preparar",                    g:3, lv:"N4" },
  { k:"質問する",   f:"しつもんする",  m:"Preguntar",                   g:3, lv:"N4" },
  { k:"掃除する",   f:"そうじする",    m:"Limpiar",                     g:3, lv:"N4" },
  { k:"洗濯する",   f:"せんたくする",  m:"Lavar la ropa",               g:3, lv:"N4" },
  { k:"到着する",   f:"とうちゃくする",m:"Llegar",                      g:3, lv:"N4" },
  { k:"返事する",   f:"へんじする",    m:"Responder / Contestar",       g:3, lv:"N4" },
];

// ═══════════════════════════════════════════
//  GRAMMAR DATA
//  IMPORTANTE: el campo "f" indica qué forma
//  necesita la gramática. En el modo gramática
//  se muestra SOLO "m" (significado), sin tag.
// ═══════════════════════════════════════════
const grammarData = [
  { f:"nai_stem", tag:"〜なければなりません",      m:"Tener que (obligación formal)",         lv:"N4", formula:"V-ない(raíz) + ければなりません",     hint:"食べる → 食べ + なければなりません",        ex:"毎日薬を飲まなければなりません。(Tengo que tomar medicina cada día.)" },
  { f:"nai_stem", tag:"〜なくてもいいです",         m:"No es necesario",                       lv:"N4", formula:"V-ない(raíz) + くてもいいです",       hint:"食べる → 食べ + なくてもいいです",          ex:"今日は来なくてもいいです。(No es necesario que vengas hoy.)" },
  { f:"te",       tag:"〜てはいけません",           m:"Está prohibido / No se permite",        lv:"N4", formula:"V-て + はいけません",                  hint:"話す → 話して + はいけません",              ex:"ここでタバコを吸ってはいけません。(Está prohibido fumar aquí.)" },
  { f:"te",       tag:"〜てもいいです",             m:"Se permite / Está bien que...",         lv:"N4", formula:"V-て + もいいです",                    hint:"食べる → 食べて + もいいです",              ex:"ここで写真を撮ってもいいです。(Está bien tomar fotos aquí.)" },
  { f:"te",       tag:"〜ています",                m:"Estar haciendo / Estado resultante",    lv:"N4", formula:"V-て + います",                        hint:"食べる → 食べています",                    ex:"今ご飯を食べています。(Ahora estoy comiendo.)" },
  { f:"te",       tag:"〜てあります",              m:"Algo está hecho con intención",         lv:"N4", formula:"V-て + あります",                      hint:"書く → 書いてあります",                    ex:"黒板に名前が書いてあります。(El nombre está escrito en la pizarra.)" },
  { f:"te",       tag:"〜ておきます",              m:"Hacer algo de antemano",                lv:"N4", formula:"V-て + おきます",                      hint:"買う → 買っておきます",                    ex:"パーティーの前に飲み物を買っておきます。(Compro bebidas antes de la fiesta.)" },
  { f:"te",       tag:"〜てしまいます",            m:"Terminar completamente / lamentablemente",lv:"N4",formula:"V-て + しまいます",                   hint:"食べる → 食べてしまいました",               ex:"ケーキを全部食べてしまいました。(Me comí todo el pastel, ay...)" },
  { f:"te",       tag:"〜てくる",                 m:"Acción que se acerca al presente / empieza a",lv:"N4",formula:"V-て + くる",                    hint:"増える → 増えてきた",                       ex:"最近、日本語が上手になってきました。(Últimamente mi japonés ha ido mejorando.)" },
  { f:"te",       tag:"〜ていく",                 m:"Acción que se aleja hacia el futuro / continúa",lv:"N4",formula:"V-て + いく",                  hint:"減る → 減っていく",                         ex:"これからもっと練習していきます。(Seguiré practicando a partir de ahora.)" },
  { f:"ta",       tag:"〜たことがあります",        m:"Haber tenido la experiencia de",        lv:"N4", formula:"V-た + ことがあります",                hint:"行く → 行ったことがあります",               ex:"富士山に登ったことがあります。(He subido al Monte Fuji alguna vez.)" },
  { f:"te",       tag:"〜てみます",               m:"Intentar hacer algo (ver qué pasa)",    lv:"N4", formula:"V-て + みます",                        hint:"食べる → 食べてみます",                    ex:"この料理を一度食べてみます。(Voy a intentar comer este platillo una vez.)" },
  { f:"ta",       tag:"〜たほうがいいです",        m:"Es mejor que... (consejo)",             lv:"N4", formula:"V-た + ほうがいいです",                hint:"寝る → 寝たほうがいいです",                ex:"早く寝たほうがいいです。(Es mejor que duermas temprano.)" },
  { f:"nai_stem", tag:"〜ないほうがいいです",      m:"Es mejor que no...",                    lv:"N4", formula:"V-ない(raíz) + ないほうがいいです",    hint:"食べる → 食べないほうがいいです",           ex:"夜遅く食べないほうがいいです。(Es mejor no comer tarde en la noche.)" },
  { f:"masu",     tag:"〜たいです",               m:"Querer hacer algo",                     lv:"N4", formula:"V-ます(raíz) + たいです",              hint:"行く → 行き + たいです",                   ex:"日本に行きたいです。(Quiero ir a Japón.)" },
  { f:"Volitivo", tag:"〜（よ）うと思っています",  m:"Estoy pensando en... (intención futura)",lv:"N4",formula:"V-volitivo + と思っています",          hint:"受ける → 受けようと思っています",           ex:"来年、N3を受けようと思っています。(Estoy pensando en tomar el N3 el próximo año.)" },
  { f:"Potencial", tag:"〜（ら）れる (Potencial)", m:"Poder hacer algo",                     lv:"N4", formula:"V-potencial",                          hint:"食べる→食べられる, 書く→書ける, する→できる", ex:"私は漢字が読めます。(Puedo leer kanji.)" },
  { f:"ta",       tag:"〜たら",                  m:"Si / Cuando algo ocurre (cond. real)",  lv:"N4", formula:"V-た + ら",                            hint:"帰る → 帰ったら",                          ex:"家に帰ったら、電話してください。(Cuando llegues a casa, llámame.)" },
  { f:"te",       tag:"〜てあげる",              m:"Hacer un favor a alguien (yo→otro)",    lv:"N4", formula:"V-て + あげる",                        hint:"教える → 教えてあげる",                    ex:"友達に日本語を教えてあげました。(Le enseñé japonés a mi amigo.)" },
  { f:"te",       tag:"〜てくれる",              m:"Alguien me hace un favor (otro→yo)",    lv:"N4", formula:"V-て + くれる",                        hint:"手伝う → 手伝ってくれた",                  ex:"友達が手伝ってくれました。(Mi amigo me ayudó.)" },
  { f:"te",       tag:"〜てもらう",              m:"Recibir un favor de alguien",           lv:"N4", formula:"V-て + もらう",                        hint:"直す → 直してもらった",                    ex:"先生に作文を直してもらいました。(Recibí que el profesor corrigiera mi redacción.)" },
  { f:"masu",     tag:"〜に行く / 来る",          m:"Ir / Venir a hacer algo (propósito)",   lv:"N4", formula:"V-ます(raíz) + に行く/来る",           hint:"食べる → 食べに行く",                      ex:"昼ご飯を食べに行きます。(Voy a comer el almuerzo.)" },
  { f:"ta",       tag:"〜たあとで",              m:"Después de hacer...",                   lv:"N4", formula:"V-た + あとで",                        hint:"食べる → 食べたあとで",                    ex:"宿題をしたあとで、ゲームをします。(Después de hacer la tarea, juego videojuegos.)" },
  { f:"te",       tag:"〜てから",               m:"Después de / Desde que hice...",        lv:"N4", formula:"V-て + から",                          hint:"食べる → 食べてから",                      ex:"シャワーを浴びてから、寝ます。(Después de ducharme, me voy a dormir.)" },
  { f:"masu",     tag:"〜ながら",               m:"Mientras se hace otra cosa (simultáneo)",lv:"N4",formula:"V-ます(raíz) + ながら",                hint:"聞く → 聞き + ながら",                     ex:"音楽を聞きながら勉強します。(Estudio mientras escucho música.)" },
  { f:"masu",     tag:"〜すぎる",               m:"Hacer algo en exceso / demasiado",      lv:"N4", formula:"V-ます(raíz) / Adj + すぎる",          hint:"食べる → 食べ + すぎる",                   ex:"昨日食べすぎて、お腹が痛いです。(Ayer comí demasiado y me duele el estómago.)" },
  { f:"masu",     tag:"〜やすい",               m:"Fácil de hacer",                        lv:"N4", formula:"V-ます(raíz) + やすい",                hint:"使う → 使い + やすい",                     ex:"このペンは書きやすいです。(Este bolígrafo es fácil de escribir.)" },
  { f:"masu",     tag:"〜にくい",               m:"Difícil de hacer",                      lv:"N4", formula:"V-ます(raíz) + にくい",                hint:"読む → 読み + にくい",                     ex:"この字は読みにくいです。(Esta letra es difícil de leer.)" },
  { f:"masu",     tag:"〜方（かた）",            m:"Manera de hacer algo",                  lv:"N4", formula:"V-ます(raíz) + 方",                   hint:"食べる → 食べ + 方",                       ex:"この料理の作り方を教えてください。(Por favor enséñame cómo hacer esta comida.)" },
  { f:"masu",     tag:"〜だす",                m:"Empezar a (de repente / inesperadamente)",lv:"N4",formula:"V-ます(raíz) + だす",                  hint:"走る → 走り + だす",                       ex:"急に走り出した。(De repente se echó a correr.)" },
  { f:"masu",     tag:"〜おわる",              m:"Terminar de hacer",                      lv:"N4", formula:"V-ます(raíz) + おわる",                hint:"食べる → 食べ + おわる",                   ex:"宿題を書きおわりました。(Terminé de escribir la tarea.)" },
  { f:"dic",      tag:"〜ようになる",           m:"Llegar a ser capaz de / empezar a",     lv:"N4", formula:"V-dic + ようになる",                   hint:"話せる + ようになった",                    ex:"練習して、泳げるようになりました。(Con práctica, llegué a poder nadar.)" },
  { f:"dic",      tag:"〜ようにする",           m:"Intentar / asegurarse de hacer",        lv:"N4", formula:"V-dic + ようにする",                   hint:"食べる + ようにする",                      ex:"毎日野菜を食べるようにしています。(Me aseguro de comer verduras cada día.)" },
  { f:"Pasiva",   tag:"〜られる (Pasiva)",      m:"Ser hecho por alguien (voz pasiva)",    lv:"N4", formula:"V-pasivo",                             hint:"叱る→叱られる, 食べる→食べられる, 書く→書かれる", ex:"先生に叱られました。(Fui regañada por el/la maestro/a.)" },
  { f:"ta",       tag:"〜たばかり",            m:"Acabar de hacer algo",                  lv:"N4", formula:"V-た + ばかり",                        hint:"食べる → 食べたばかりです",                ex:"さっきご飯を食べたばかりです。(Acabo de comer hace un momento.)" },
  { f:"dic",      tag:"〜まえに",              m:"Antes de hacer...",                     lv:"N4", formula:"V-dic + まえに",                       hint:"寝る → 寝るまえに",                        ex:"寝る前に歯を磨きます。(Me lavo los dientes antes de dormir.)" },
  { f:"dic",      tag:"〜ために",              m:"Para / Con el fin de (propósito)",      lv:"N4", formula:"V-dic / Sust + の + ために",           hint:"合格する → 合格するために",                ex:"試験に合格するために、毎日勉強します。(Estudio cada día para aprobar el examen.)" },
  { f:"dic",      tag:"〜ように",              m:"De modo que / Para que (objetivo)",     lv:"N4", formula:"V-dic / V-nai + ように",              hint:"忘れない + ように",                        ex:"忘れないようにメモします。(Anoto para no olvidar.)" },
  { f:"dic",      tag:"〜ことができる",         m:"Ser capaz de / Poder hacer",            lv:"N4", formula:"V-dic + ことができる",                 hint:"泳ぐ → 泳ぐことができます",                ex:"私は日本語を話すことができます。(Puedo hablar japonés.)" },
  { f:"dic",      tag:"〜ことにする",          m:"Decidir hacer algo (decisión propia)",  lv:"N4", formula:"V-dic + ことにする",                   hint:"行く → 行くことにした",                    ex:"日本に留学することにしました。(Decidí estudiar en Japón.)" },
  { f:"dic",      tag:"〜ことになる",          m:"Resultar que / Quedar decidido que",    lv:"N4", formula:"V-dic + ことになる",                   hint:"転勤する → 転勤することになった",           ex:"来月、東京に引っ越すことになりました。(Ha quedado decidido que me mudo a Tokio el próximo mes.)" },
  { f:"dic",      tag:"〜ところです",          m:"Estar a punto de / justo haciendo / acabar de",lv:"N4",formula:"V-dic/て-いる/た + ところです",  hint:"食べるところ / 食べているところ / 食べたところ", ex:"今から食べるところです。(Estoy a punto de comer.)" },
  { f:"dic",      tag:"〜はずです",           m:"Se supone que / Debería ser",           lv:"N4", formula:"V-dic / Adj + はずです",               hint:"来る → 来るはずです",                      ex:"彼は今日来るはずです。(Se supone que él viene hoy.)" },
  { f:"dic",      tag:"〜はずがない",          m:"Es imposible que / No puede ser que",   lv:"N4", formula:"V-dic / Adj + はずがない",             hint:"知る → 知るはずがない",                    ex:"あの人がそんなことをするはずがない。(Es imposible que esa persona haga tal cosa.)" },
  { f:"dic",      tag:"〜のに",               m:"A pesar de que / Aunque (contraste)",   lv:"N4", formula:"V-dic + のに",                        hint:"頑張った + のに",                          ex:"頑張ったのに、試験に落ちた。(A pesar de que me esforcé, reprobé el examen.)" },
  { f:"dic",      tag:"〜ので",               m:"Porque / Debido a (formal, causa objetiva)",lv:"N4",formula:"V-dic + ので",                     hint:"遅れる → 遅れるので",                      ex:"電車が遅れているので、少し遅くなります。(Porque el tren está retrasado, llegaré un poco tarde.)" },
  { f:"dic",      tag:"〜んです / のです",     m:"Es que... (explicación o énfasis)",     lv:"N4", formula:"V-dic + んです",                      hint:"疲れた → 疲れたんです",                    ex:"実は昨日眠れなかったんです。(Es que ayer no pude dormir.)" },
  { f:"ta",       tag:"〜たら〜た",           m:"Cuando hice X, Y ocurrió (resultado inesperado)",lv:"N4",formula:"V-た + ら + resultado pasado", hint:"開けたら → 猫がいた",                      ex:"ドアを開けたら、猫がいた。(Cuando abrí la puerta, había un gato.)" },
  { f:"masu",     tag:"〜そうです（様態）",    m:"Parece que... / Tiene pinta de (apariencia)",lv:"N4",formula:"V-ます(raíz) / Adj(raíz) + そうです",hint:"おいしい → おいしそうです",               ex:"このケーキはおいしそうです。(Este pastel parece estar delicioso.)" },
  { f:"dic",      tag:"〜そうです（伝聞）",    m:"He oído que / Dicen que (información de otros)",lv:"N4",formula:"V-dic + そうです",              hint:"来る → 来るそうです",                      ex:"明日雨が降るそうです。(Dicen que mañana lloverá.)" },
  { f:"dic",      tag:"〜でしょう / だろう",   m:"Probablemente / ¿Verdad? (suposición)",  lv:"N4", formula:"V-dic + でしょう",                    hint:"来る → 来るでしょう",                      ex:"明日は晴れるでしょう。(Probablemente mañana hará buen tiempo.)" },
  { f:"dic",      tag:"〜かもしれません",      m:"Quizás / Tal vez (posibilidad)",        lv:"N4", formula:"V-dic + かもしれません",               hint:"来る → 来るかもしれません",                ex:"彼は来ないかもしれません。(Quizás él no venga.)" },
  { f:"dic",      tag:"〜ようです",           m:"Parece que... (conjetura propia)",      lv:"N4", formula:"V-dic + ようです",                    hint:"知っている → 知っているようです",           ex:"彼女は疲れているようです。(Parece que ella está cansada.)" },
  { f:"dic",      tag:"〜らしいです",         m:"Parece / Se dice que (típico de / evidencia)",lv:"N4",formula:"V-dic + らしいです",              hint:"来る → 来るらしい",                        ex:"彼は来ないらしいです。(Al parecer él no viene.)" },
  { f:"dic",      tag:"〜なら",              m:"Si es el caso de / Si se trata de",     lv:"N4", formula:"V-dic / Sust + なら",                 hint:"行くなら / 東京なら",                      ex:"東京に行くなら、スカイツリーに登ってください。(Si vas a Tokio, sube al Skytree.)" },
  { f:"dic",      tag:"〜し〜し",            m:"Además... también... (enlista razones)", lv:"N4", formula:"V-dic + し + V-dic + し",            hint:"安い + し、おいしい + し",                 ex:"この店は安いし、おいしいし、また来たいです。(Esta tienda es barata y además está rica, quiero volver.)" },
  { f:"masu",     tag:"〜てほしい",          m:"Querer que alguien haga algo",          lv:"N4", formula:"V-て + ほしい",                       hint:"来る → 来てほしい",                        ex:"もっと話してほしいです。(Quiero que hables más.)" },
  { f:"dic",      tag:"〜うちに",            m:"Mientras / Antes de que cambie el estado",lv:"N4",formula:"V-dic / V-nai + うちに",             hint:"若い + うちに",                            ex:"若いうちに、いろんな国を旅行したいです。(Quiero viajar a varios países mientras soy joven.)" },
  { f:"dic",      tag:"〜かどうか",          m:"Si... o no (pregunta indirecta)",       lv:"N4", formula:"V-dic + かどうか",                    hint:"来る + かどうか",                          ex:"彼が来るかどうか分かりません。(No sé si él vendrá o no.)" },
  { f:"dic",      tag:"〜について",          m:"Sobre / Acerca de",                     lv:"N4", formula:"Sust + について",                     hint:"日本語 + について",                        ex:"日本語の文法について質問があります。(Tengo una pregunta sobre la gramática japonesa.)" },
  { f:"dic",      tag:"〜によって",          m:"Por (agente) / Según / Dependiendo de", lv:"N4", formula:"Sust + によって",                     hint:"人 + によって",                            ex:"人によって意見が違います。(Las opiniones varían según la persona.)" },
  { f:"masu",     tag:"〜ばかり",            m:"Solo / Nada más que (exceso de algo)",  lv:"N4", formula:"V-て + ばかり / Sust + ばかり",        hint:"ゲームをして + ばかり",                    ex:"ゲームばかりしないで、勉強しなさい。(No hagas solo videojuegos, estudia.)" },
  { f:"ta",       tag:"〜たばかり",          m:"Acabar de hacer (reciente)",            lv:"N4", formula:"V-た + ばかり",                       hint:"食べた + ばかり",                          ex:"さっきご飯を食べたばかりです。(Acabo de comer hace un momento.)" },
];

// ═══════════════════════════════════════════
//  STAR DATA — Formato JLPT auténtico
//  parts[]: las 4 opciones numeradas 1〜4
//  order[]: el orden correcto de las 4 partes
//           para formar la oración completa
//  starIndex: cuál de las 4 partes va en ★
//             (posición 3 en el orden, 1-based en parts)
//  La oración tiene 6 slots:
//    [pre] __ __ ★ __ [post]
//  El ★ es siempre la 3ª de las 4 partes ordenadas.
// ═══════════════════════════════════════════
const starData = [
  {
    lv:"N4", grammar:"〜なければなりません",
    pre:"毎日", post:"。",
    parts:["薬を","飲ま","なければ","なりません"],
    order:[1,2,3,4], starIndex:3,
    translation:"Todos los días tengo que tomar la medicina."
  },
  {
    lv:"N4", grammar:"〜たことがあります",
    pre:"私は", post:"。",
    parts:["登った","富士山に","こと","があります"],
    order:[2,1,3,4], starIndex:3,
    translation:"He subido al Monte Fuji alguna vez."
  },
  {
    lv:"N4", grammar:"〜てもいいです",
    pre:"ここで", post:"か？",
    parts:["撮っ","ても","写真を","いいです"],
    order:[3,1,2,4], starIndex:2,
    translation:"¿Está bien tomar fotos aquí?"
  },
  {
    lv:"N4", grammar:"〜てはいけません",
    pre:"図書館で", post:"。",
    parts:["大きな","話し","声で","てはいけません"],
    order:[1,3,2,4], starIndex:2,
    translation:"No se permite hablar en voz alta en la biblioteca."
  },
  {
    lv:"N4", grammar:"〜ようになりました",
    pre:"練習して", post:"。",
    parts:["ように","漢字が","なりました","読める"],
    order:[2,4,1,3], starIndex:1,
    translation:"Con práctica, llegué a poder leer kanji."
  },
  {
    lv:"N4", grammar:"〜てから",
    pre:"シャワーを", post:"。",
    parts:["から","浴び","寝ます","て"],
    order:[2,4,1,3], starIndex:1,
    translation:"Después de ducharme, me voy a dormir."
  },
  {
    lv:"N4", grammar:"〜たほうがいいです",
    pre:"風邪の", post:"。",
    parts:["は","ほうがいいです","早く寝た","とき"],
    order:[4,1,3,2], starIndex:3,
    translation:"Cuando tienes resfriado, es mejor dormir temprano."
  },
  {
    lv:"N4", grammar:"〜てもらいました",
    pre:"友達に", post:"。",
    parts:["て","もらいました","荷物を","持っ"],
    order:[3,4,1,2], starIndex:1,
    translation:"Le pedí a mi amigo que me cargara el equipaje."
  },
  {
    lv:"N4", grammar:"〜ながら",
    pre:"", post:"勉強します。",
    parts:["を","ながら","音楽","聞き"],
    order:[3,1,4,2], starIndex:4,
    translation:"Estudio mientras escucho música."
  },
  {
    lv:"N4", grammar:"〜ておきます",
    pre:"パーティーの", post:"。",
    parts:["買っ","飲み物を","ておきます","前に"],
    order:[4,2,1,3], starIndex:1,
    translation:"Antes de la fiesta, compraré bebidas de antemano."
  },
  {
    lv:"N4", grammar:"〜てしまいました",
    pre:"大事な", post:"。",
    parts:["し","なく","書類を","てしまいました"],
    order:[3,2,1,4], starIndex:1,
    translation:"Por desgracia perdí un documento importante."
  },
  {
    lv:"N4", grammar:"〜たら",
    pre:"春に", post:"。",
    parts:["花見をしましょう","なっ","た","ら"],
    order:[2,3,4,1], starIndex:4,
    translation:"Cuando llegue la primavera, hagamos hanami."
  },
  {
    lv:"N4", grammar:"〜てくれました",
    pre:"先生が", post:"。",
    parts:["くれました","作文を","直し","て"],
    order:[2,3,4,1], starIndex:4,
    translation:"El/La profesor/a me corrigió la redacción."
  },
  {
    lv:"N4", grammar:"〜すぎます",
    pre:"この", post:"。",
    parts:["重","バッグは","ぎます","す"],
    order:[2,1,4,3], starIndex:4,
    translation:"Esta bolsa es demasiado pesada."
  },
  {
    lv:"N4", grammar:"〜たばかりです",
    pre:"さっき", post:"。",
    parts:["食べ","た","ばかりです","ご飯を"],
    order:[4,1,2,3], starIndex:2,
    translation:"Acabo de comer hace un momento."
  },
  {
    lv:"N4", grammar:"〜てみます",
    pre:"この料理を", post:"。",
    parts:["一度","てみます","作っ","作り"],
    order:[1,3,2,4], starIndex:2,
    translation:"Voy a intentar hacer esta comida una vez."
  },
  {
    lv:"N4", grammar:"〜ようにしています",
    pre:"毎日", post:"。",
    parts:["食べる","野菜を","よう","にしています"],
    order:[2,1,3,4], starIndex:3,
    translation:"Me aseguro de comer verduras todos los días."
  },
  {
    lv:"N4", grammar:"〜てあげました",
    pre:"道に迷っている", post:"。",
    parts:["てあげました","人に","教え","道を"],
    order:[2,4,3,1], starIndex:3,
    translation:"Le indiqué el camino a una persona que estaba perdida."
  },
  {
    lv:"N4", grammar:"〜やすいです",
    pre:"この", post:"。",
    parts:["アプリは","やすい","使い","です"],
    order:[1,3,2,4], starIndex:2,
    translation:"Esta aplicación es fácil de usar."
  },
  {
    lv:"N4", grammar:"〜られました（受身）",
    pre:"授業中に", post:"。",
    parts:["名前を","先生に","呼ば","れました"],
    order:[2,1,3,4], starIndex:3,
    translation:"Durante la clase, el/la profesor/a me llamó por mi nombre."
  },
  {
    lv:"N4", grammar:"〜かもしれません",
    pre:"明日は", post:"。",
    parts:["雨が","降る","かも","しれません"],
    order:[1,2,3,4], starIndex:3,
    translation:"Quizás mañana llueva."
  },
  {
    lv:"N4", grammar:"〜ために",
    pre:"試験に", post:"毎日勉強します。",
    parts:["するために","合格","一生懸命","を"],
    order:[2,4,1,3], starIndex:1,
    translation:"Estudio todos los días con todas mis fuerzas para aprobar el examen."
  },
  {
    lv:"N4", grammar:"〜ことができます",
    pre:"私は", post:"。",
    parts:["話す","日本語を","ことが","できます"],
    order:[2,1,3,4], starIndex:3,
    translation:"Puedo hablar japonés."
  },
  {
    lv:"N4", grammar:"〜ことにしました",
    pre:"来年、", post:"。",
    parts:["することに","日本に","しました","留学"],
    order:[2,4,1,3], starIndex:1,
    translation:"Decidí estudiar en Japón el próximo año."
  },
  {
    lv:"N4", grammar:"〜はずです",
    pre:"彼は", post:"。",
    parts:["今日","来る","はず","です"],
    order:[1,2,3,4], starIndex:3,
    translation:"Se supone que él viene hoy."
  },
];
