const verbData = [

  // =========================
  // N4
  // =========================

  { k: "開く", f: "あく", m: "Abrirse", g: 1, lv: "N4" },
  { k: "開ける", f: "あける", m: "Abrir", g: 2, lv: "N4" },
  { k: "集まる", f: "あつまる", m: "Reunirse", g: 1, lv: "N4" },
  { k: "集める", f: "あつめる", m: "Reunir", g: 2, lv: "N4" },
  { k: "足す", f: "たす", m: "Sumar / Añadir", g: 1, lv: "N4" },
  { k: "謝る", f: "あやまる", m: "Disculparse", g: 1, lv: "N4" },
  { k: "安心する", f: "あんしんする", m: "Tranquilizarse", g: 3, lv: "N4" },
  { k: "案内する", f: "あんないする", m: "Guiar / Mostrar", g: 3, lv: "N4" },
  { k: "生きる", f: "いきる", m: "Vivir", g: 2, lv: "N4" },
  { k: "急ぐ", f: "いそぐ", m: "Apresurarse", g: 1, lv: "N4" },
  { k: "祈る", f: "いのる", m: "Rezar / Orar", g: 1, lv: "N4" },
  { k: "いらっしゃる", f: "いらっしゃる", m: "Estar / Ir / Venir (Honorífico)", g: 1, lv: "N4" },
  { k: "致す", f: "いたす", m: "Hacer (Humilde)", g: 1, lv: "N4" },
  { k: "植える", f: "うえる", m: "Plantar", g: 2, lv: "N4" },
  { k: "伺う", f: "うかがう", m: "Visitar / Preguntar (Humilde)", g: 1, lv: "N4" },
  { k: "受ける", f: "うける", m: "Recibir / Tomar (examen)", g: 2, lv: "N4" },
  { k: "動く", f: "うごく", m: "Moverse", g: 1, lv: "N4" },
  { k: "動かす", f: "うごかす", m: "Mover algo", g: 1, lv: "N4" },
  { k: "打つ", f: "うつ", m: "Golpear / Teclear", g: 1, lv: "N4" },
  { k: "写す", f: "うつす", m: "Copiar / Fotografiar", g: 1, lv: "N4" },
  { k: "移る", f: "うつる", m: "Mudarse / Trasladarse", g: 1, lv: "N4" },
  { k: "選ぶ", f: "えらぶ", m: "Elegir", g: 1, lv: "N4" },
  { k: "起きる", f: "おきる", m: "Despertarse / Ocurrir", g: 2, lv: "N4" },
  { k: "送る", f: "おくる", m: "Enviar / Acompañar", g: 1, lv: "N4" },
  { k: "怒る", f: "おこる", m: "Enojarse", g: 1, lv: "N4" },
  { k: "落ちる", f: "おちる", m: "Caer", g: 2, lv: "N4" },
  { k: "落とす", f: "おとす", m: "Dejar caer", g: 1, lv: "N4" },
  { k: "踊る", f: "おどる", m: "Bailar", g: 1, lv: "N4" },
  { k: "驚く", f: "おどろく", m: "Sorprenderse", g: 1, lv: "N4" },
  { k: "思い出す", f: "おもいだす", m: "Recordar", g: 1, lv: "N4" },
  { k: "思う", f: "おもう", m: "Pensar / Creer", g: 1, lv: "N4" },
  { k: "折る", f: "おる", m: "Doblar / Romper", g: 1, lv: "N4" },
  { k: "折れる", f: "おれる", m: "Doblarse / Romperse", g: 2, lv: "N4" },
  { k: "下りる", f: "おりる", m: "Bajar (de un lugar alto)", g: 2, lv: "N4" },
  { k: "降る", f: "ふる", m: "Llover / Nevar", g: 1, lv: "N4" },
  { k: "飾る", f: "かざる", m: "Decorar", g: 1, lv: "N4" },
  { k: "片付ける", f: "かたづける", m: "Ordenar / Limpiar", g: 2, lv: "N4" },
  { k: "勝つ", f: "かつ", m: "Ganar", g: 1, lv: "N4" },
  { k: "替える", f: "かえる", m: "Reemplazar / Cambiar", g: 2, lv: "N4" },
  { k: "変える", f: "かえる", m: "Cambiar algo", g: 2, lv: "N4" },
  { k: "変わる", f: "かわる", m: "Cambiar (intransitivo)", g: 1, lv: "N4" },
  { k: "通う", f: "かよう", m: "Ir y venir (frecuentar)", g: 1, lv: "N4" },
  { k: "乾く", f: "かわく", m: "Secarse", g: 1, lv: "N4" },
  { k: "乾かす", f: "かわかす", m: "Secar algo", g: 1, lv: "N4" },
  { k: "考える", f: "かんがえる", m: "Pensar / Considerar", g: 2, lv: "N4" },
  { k: "頑張る", f: "がんばる", m: "Esforzarse", g: 1, lv: "N4" },
  { k: "聞く", f: "きく", m: "Escuchar / Preguntar", g: 1, lv: "N4" },
  { k: "聞こえる", f: "きこえる", m: "Oírse / Ser audible", g: 2, lv: "N4" },
  { k: "決まる", f: "きまる", m: "Decidirse", g: 1, lv: "N4" },
  { k: "決める", f: "きめる", m: "Decidir", g: 2, lv: "N4" },

  { k: "切る", f: "きる", m: "Cortar", g: 1, lv: "N4" },
  { k: "着る", f: "きる", m: "Vestirse (torso)", g: 2, lv: "N4" },
  { k: "比べる", f: "くらべる", m: "Comparar", g: 2, lv: "N4" },
  { k: "くれる", f: "くれる", m: "Darme (a mí)", g: 2, lv: "N4" },
  { k: "暮らす", f: "くらす", m: "Vivir / Pasar el tiempo", g: 1, lv: "N4" },
  { k: "繰り返す", f: "くりかえす", m: "Repetir", g: 1, lv: "N4" },
  { k: "消える", f: "きえる", m: "Apagarse / Desaparecer", g: 2, lv: "N4" },
  { k: "消す", f: "けす", m: "Apagar / Borrar", g: 1, lv: "N4" },
  { k: "答える", f: "こたえる", m: "Responder", g: 2, lv: "N4" },
  { k: "困る", f: "こまる", m: "Estar en apuros", g: 1, lv: "N4" },
  { k: "混む", f: "こむ", m: "Llenarse / Estar abarrotado", g: 1, lv: "N4" },
  { k: "殺す", f: "ころす", m: "Matar", g: 1, lv: "N4" },
  { k: "壊れる", f: "こわれる", m: "Romperse", g: 2, lv: "N4" },
  { k: "壊す", f: "こわす", m: "Romper algo", g: 1, lv: "N4" },
  { k: "捜す", f: "さがす", m: "Buscar (algo perdido)", g: 1, lv: "N4" },
  { k: "探す", f: "さがす", m: "Buscar (algo deseado)", g: 1, lv: "N4" },
  { k: "下がる", f: "さがる", m: "Bajar / Retroceder", g: 1, lv: "N4" },
  { k: "下げる", f: "さげる", m: "Bajar algo / Agachar", g: 2, lv: "N4" },
  { k: "差し上げる", f: "さしあげる", m: "Dar (Honorífico)", g: 2, lv: "N4" },
  { k: "騒ぐ", f: "さわぐ", m: "Hacer ruido / Escándalo", g: 1, lv: "N4" },
  { k: "触る", f: "さわる", m: "Tocar", g: 1, lv: "N4" },
  { k: "叱る", f: "しかる", m: "Regañar", g: 1, lv: "N4" },
  { k: "調べる", f: "しらべる", m: "Investigar / Revisar", g: 2, lv: "N4" },
  { k: "知らせる", f: "しらせる", m: "Informar / Notificar", g: 2, lv: "N4" },
  { k: "信じる", f: "しんじる", m: "Creer / Confiar", g: 2, lv: "N4" },
  { k: "進む", f: "すすむ", m: "Avanzar / Progresar", g: 1, lv: "N4" },
  { k: "捨てる", f: "すてる", m: "Tirar / Desechar", g: 2, lv: "N4" },
  { k: "滑る", f: "すべる", m: "Resbalar", g: 1, lv: "N4" },
  { k: "済む", f: "すむ", m: "Terminar / Finalizar", g: 1, lv: "N4" },
  { k: "座る", f: "すわる", m: "Sentarse", g: 1, lv: "N4" },
  { k: "育つ", f: "そだつ", m: "Crecer / Criarse", g: 1, lv: "N4" },
  { k: "育てる", f: "そだてる", m: "Criar / Educar", g: 2, lv: "N4" },
  { k: "倒れる", f: "たおれる", m: "Caerse / Desmayarse", g: 2, lv: "N4" },
  { k: "倒す", f: "たおす", m: "Derribar algo", g: 1, lv: "N4" },
  { k: "出す", f: "だす", m: "Sacar / Enviar", g: 1, lv: "N4" },
  { k: "訪ねる", f: "たずねる", m: "Visitar", g: 2, lv: "N4" },
  { k: "尋ねる", f: "たずねる", m: "Preguntar", g: 2, lv: "N4" },
  { k: "建てる", f: "たてる", m: "Construir", g: 2, lv: "N4" },
  { k: "立てる", f: "たてる", m: "Levantar / Poner de pie", g: 2, lv: "N4" },
  { k: "足りる", f: "たりる", m: "Ser suficiente", g: 2, lv: "N4" },
  { k: "食べる", f: "たべる", m: "Comer", g: 2, lv: "N4" },
  { k: "試す", f: "ためす", m: "Probar / Intentar", g: 1, lv: "N4" },
  { k: "楽しむ", f: "たのしむ", m: "Disfrutar", g: 1, lv: "N4" },
  { k: "頼む", f: "たのむ", m: "Pedir / Solicitar", g: 1, lv: "N4" },
  { k: "違う", f: "ちがう", m: "Ser diferente / Equivocarse", g: 1, lv: "N4" },
  { k: "使う", f: "つかう", m: "Usar", g: 1, lv: "N4" },
  { k: "捕まえる", f: "つかまえる", m: "Atrapar / Capturar", g: 2, lv: "N4" },
  { k: "疲れる", f: "つかれる", m: "Cansarse", g: 2, lv: "N4" },
  { k: "着く", f: "つく", m: "Llegar", g: 1, lv: "N4" },
  { k: "付ける", f: "つける", m: "Encender / Pegar / Adjuntar", g: 2, lv: "N4" },

{ k: "点ける", f: "つける", m: "Encender (luz/aparatos)", g: 2, lv: "N4" },
  { k: "浸ける", f: "つける", m: "Remojar / Sumergir", g: 2, lv: "N4" },
  { k: "伝える", f: "つたえる", m: "Comunicar / Transmitir", g: 2, lv: "N4" },
  { k: "続く", f: "つづく", m: "Continuar (intransitivo)", g: 1, lv: "N4" },
  { k: "続ける", f: "つづける", m: "Continuar algo (transitivo)", g: 2, lv: "N4" },
  { k: "包む", f: "つつむ", m: "Envolver / Empacar", g: 1, lv: "N4" },
  { k: "勤める", f: "つとめる", m: "Trabajar para alguien", g: 2, lv: "N4" },
  { k: "釣る", f: "つる", m: "Pescar", g: 1, lv: "N4" },
  { k: "連れて行く", f: "つれていく", m: "Llevar a alguien", g: 3, lv: "N4" },
  { k: "連れて来る", f: "つれてくる", m: "Traer a alguien", g: 3, lv: "N4" },
  { k: "手伝う", f: "てつだう", m: "Ayudar", g: 1, lv: "N4" },
  { k: "出掛ける", f: "でかける", m: "Salir (de casa)", g: 2, lv: "N4" },
  { k: "出来る", f: "できる", m: "Poder / Estar listo", g: 2, lv: "N4" },
  { k: "通る", f: "とおる", m: "Pasar por / Atravesar", g: 1, lv: "N4" },
  { k: "届く", f: "とどく", m: "Llegar / Alcanzar", g: 1, lv: "N4" },
  { k: "届ける", f: "とどける", m: "Entregar / Notificar", g: 2, lv: "N4" },
  { k: "泊まる", f: "とまる", m: "Hospedarse / Quedarse", g: 1, lv: "N4" },
  { k: "止まる", f: "とまる", m: "Detenerse", g: 1, lv: "N4" },
  { k: "止める", f: "とめる", m: "Detener algo", g: 2, lv: "N4" },
  { k: "取り替える", f: "とりかえる", m: "Cambiar / Intercambiar", g: 2, lv: "N4" },
  { k: "取る", f: "とる", m: "Tomar / Coger", g: 1, lv: "N4" },
  { k: "撮る", f: "とる", m: "Tomar (fotos)", g: 1, lv: "N4" },
  { k: "直る", f: "なおる", m: "Arreglarse / Repararse", g: 1, lv: "N4" },
  { k: "直す", f: "なおす", m: "Arreglar / Reparar / Traducir", g: 1, lv: "N4" },
  { k: "治る", f: "なおる", m: "Sanar / Curarse", g: 1, lv: "N4" },
  { k: "亡くなる", f: "なくなる", m: "Fallecer", g: 1, lv: "N4" },
  { k: "無くなる", f: "なくなる", m: "Perderse / Desaparecer", g: 1, lv: "N4" },
  { k: "無くす", f: "なくす", m: "Perder algo", g: 1, lv: "N4" },
  { k: "投げる", f: "なげる", m: "Lanzar / Tirar", g: 2, lv: "N4" },
  { k: "慣れる", f: "なれる", m: "Acostumbrarse", g: 2, lv: "N4" },
  { k: "並ぶ", f: "ならぶ", m: "Hacer fila / Alinearse", g: 1, lv: "N4" },
  { k: "並べる", f: "ならべる", m: "Alinear / Poner en fila", g: 2, lv: "N4" },
  { k: "鳴る", f: "なる", m: "Sonar / Resonar", g: 1, lv: "N4" },
  { k: "なる", f: "なる", m: "Convertirse / Llegar a ser", g: 1, lv: "N4" },
  { k: "脱ぐ", f: "ぬぐ", m: "Desvestirse / Quitarse ropa", g: 1, lv: "N4" },
  { k: "盗む", f: "ぬすむ", m: "Robar", g: 1, lv: "N4" },
  { k: "塗る", f: "ぬる", m: "Pintar / Untar", g: 1, lv: "N4" },
  { k: "濡れる", f: "ぬれる", m: "Mojarse", g: 2, lv: "N4" },
  { k: "願う", f: "ねがう", m: "Desear / Pedir", g: 1, lv: "N4" },
  { k: "寝る", f: "ねる", m: "Dormir / Acostarse", g: 2, lv: "N4" },
  { k: "登る", f: "のぼる", m: "Escalar / Subir", g: 1, lv: "N4" },
  { k: "残る", f: "のこる", m: "Quedar / Sobrar", g: 1, lv: "N4" },
  { k: "乗り換える", f: "のりかえる", m: "Trasbordar / Cambiar transporte", g: 2, lv: "N4" },
  { k: "乗る", f: "のる", m: "Subir a un transporte", g: 1, lv: "N4" },
  { k: "運ぶ", f: "はこぶ", m: "Transportar / Cargar", g: 1, lv: "N4" },
  { k: "始まる", f: "はじまる", m: "Empezar (intransitivo)", g: 1, lv: "N4" },
  { k: "始める", f: "はじめる", m: "Empezar algo (transitivo)", g: 2, lv: "N4" },
  { k: "働く", f: "はたらく", m: "Trabajar", g: 1, lv: "N4" },
  { k: "払う", f: "はらう", m: "Pagar", g: 1, lv: "N4" },
  { k: "晴れる", f: "はれる", m: "Despejarse (clima)", g: 2, lv: "N4" },

{ k: "冷える", f: "ひえる", m: "Enfriarse", g: 2, lv: "N4" },
  { k: "冷やす", f: "ひやす", m: "Enfriar algo", g: 1, lv: "N4" },
  { k: "光る", f: "ひかる", m: "Brillar", g: 1, lv: "N4" },
  { k: "引き出す", f: "ひきだす", m: "Retirar (dinero) / Extraer", g: 1, lv: "N4" },
  { k: "引く", f: "ひく", m: "Tirar / Jalar", g: 1, lv: "N4" },
  { k: "弾く", f: "ひく", m: "Tocar (instrumento de cuerda)", g: 1, lv: "N4" },
  { k: "引っ越す", f: "ひっこす", m: "Mudarse", g: 1, lv: "N4" },
  { k: "開く", f: "ひらく", m: "Abrir (un evento/libro/ojos)", g: 1, lv: "N4" },
  { k: "拾う", f: "ひろう", m: "Recoger / Encontrar", g: 1, lv: "N4" },
  { k: "増える", f: "ふえる", m: "Aumentar (intransitivo)", g: 2, lv: "N4" },
  { k: "増やす", f: "ふやす", m: "Aumentar algo (transitivo)", g: 1, lv: "N4" },
  { k: "太る", f: "ふとる", m: "Engordar", g: 1, lv: "N4" },
  { k: "踏む", f: "ふむ", m: "Pisar", g: 1, lv: "N4" },
  { k: "振る", f: "ふる", m: "Sacudir / Agitar / Rechazar", g: 1, lv: "N4" },
  { k: "褒める", f: "ほめる", m: "Alabar / Elogiar", g: 2, lv: "N4" },
  { k: "負ける", f: "まける", m: "Perder (una batalla/juego)", g: 2, lv: "N4" },
  { k: "間違える", f: "まちがえる", m: "Equivocarse", g: 2, lv: "N4" },
  { k: "間に合う", f: "まにあう", m: "Llegar a tiempo", g: 1, lv: "N4" },
  { k: "守る", f: "まもる", m: "Proteger / Cumplir (promesa)", g: 1, lv: "N4" },
  { k: "迷う", f: "まよう", m: "Perderse / Estar indeciso", g: 1, lv: "N4" },
  { k: "見つかる", f: "みつかる", m: "Ser encontrado", g: 1, lv: "N4" },
  { k: "見つける", f: "みつける", m: "Encontrar", g: 2, lv: "N4" },
  { k: "見せる", f: "みせる", m: "Mostrar", g: 2, lv: "N4" },
  { k: "見る", f: "みる", m: "Ver / Mirar", g: 2, lv: "N4" },
  { k: "診る", f: "みる", m: "Examinar (médico)", g: 2, lv: "N4" },
  { k: "向かう", f: "むかう", m: "Dirigirse a", g: 1, lv: "N4" },
  { k: "迎える", f: "むかえる", m: "Recibir / Ir a buscar (alguien)", g: 2, lv: "N4" },
  { k: "召し上がる", f: "めしあがる", m: "Comer / Beber (Honorífico)", g: 1, lv: "N4" },
  { k: "申し上げる", f: "もうしあげる", m: "Decir (Humilde)", g: 2, lv: "N4" },
  { k: "申す", f: "もうす", m: "Decir / Llamarse (Humilde)", g: 1, lv: "N4" },
  { k: "戻る", f: "もどる", m: "Regresar / Volver", g: 1, lv: "N4" },
  { k: "戻す", f: "もどす", m: "Devolver algo", g: 1, lv: "N4" },
  { k: "貰う", f: "もらう", m: "Recibir", g: 1, lv: "N4" },
  { k: "焼く", f: "やく", m: "Asar / Hornear", g: 1, lv: "N4" },
  { k: "焼ける", f: "やける", m: "Asarse / Quemarse", g: 1, lv: "N4" },
  { k: "役に立つ", f: "やくにたつ", m: "Ser útil", g: 1, lv: "N4" },
  { k: "痩せる", f: "やせる", m: "Adelgazar", g: 2, lv: "N4" },
  { k: "止む", f: "やむ", m: "Cesar / Detenerse (clima)", g: 1, lv: "N4" },
  { k: "止める", f: "やめる", m: "Dejar / Renunciar", g: 2, lv: "N4" },
  { k: "やる", f: "やる", m: "Hacer / Dar (a inferiores)", g: 1, lv: "N4" },
  { k: "汚れる", f: "よごれる", m: "Ensuciarse", g: 2, lv: "N4" },
  { k: "汚す", f: "よごす", m: "Ensuciar algo", g: 1, lv: "N4" },
  { k: "寄る", f: "よる", m: "Acercarse / Pasar por", g: 1, lv: "N4" },
  { k: "喜ぶ", f: "よろこぶ", m: "Alegrarse", g: 1, lv: "N4" },
  { k: "沸く", f: "わく", m: "Hervir", g: 1, lv: "N4" },
  { k: "沸かす", f: "わかす", m: "Hacer hervir", g: 1, lv: "N4" },
  { k: "分かる", f: "わかる", m: "Entender", g: 1, lv: "N4" },
  { k: "別れる", f: "わかれる", m: "Separarse / Dividirse", g: 2, lv: "N4" },
  { k: "忘れる", f: "わすれる", m: "Olvidar", g: 2, lv: "N4" },
  { k: "笑う", f: "わらう", m: "Reír", g: 1, lv: "N4" },

{ k: "挨拶する", f: "あいさつする", m: "Saludar", g: 3, lv: "N4" },
  { k: "運転する", f: "うんてんする", m: "Conducir", g: 3, lv: "N4" },
  { k: "運動する", f: "うんどうする", m: "Hacer ejercicio", g: 3, lv: "N4" },
  { k: "会釈する", f: "えしゃくする", m: "Hacer una reverencia", g: 3, lv: "N4" },
  { k: "遠慮する", f: "えんりょする", m: "Ser reservado / Abstenerse", g: 3, lv: "N4" },
  { k: "感謝する", f: "かんしゃする", m: "Agradecer", g: 3, lv: "N4" },
  { k: "講義する", f: "こうぎする", m: "Dar una conferencia", g: 3, lv: "N4" },
  { k: "故障する", f: "こしょうする", m: "Averiarse / Descomponerse", g: 3, lv: "N4" },
  { k: "用意する", f: "よういする", m: "Preparar", g: 3, lv: "N4" },
  { k: "紹介する", f: "しょうかいする", m: "Presentar a alguien", g: 3, lv: "N4" },
  { k: "招待する", f: "しょうたいする", m: "Invitar", g: 3, lv: "N4" },
  { k: "承知する", f: "しょうちする", m: "Consentir / Aceptar", g: 3, lv: "N4" },
  { k: "食事する", f: "しょくじする", m: "Comer / Almorzar", g: 3, lv: "N4" },
  { k: "心配する", f: "しんぱいする", m: "Preocuparse", g: 3, lv: "N4" },
  { k: "説明する", f: "せつめいする", m: "Explicar", g: 3, lv: "N4" },
  { k: "失敗する", f: "しっぱいする", m: "Fracasar / Fallar", g: 3, lv: "N4" },
  { k: "相談する", f: "そうだんする", m: "Consultar", g: 3, lv: "N4" },
  { k: "遅刻する", f: "ちこくする", m: "Llegar tarde", g: 3, lv: "N4" },
  { k: "注意する", f: "ちゅういする", m: "Tener cuidado / Advertir", g: 3, lv: "N4" },
  { k: "注文する", f: "ちゅうもんする", m: "Pedir / Hacer un pedido", g: 3, lv: "N4" },
  { k: "貯金する", f: "ちょきんする", m: "Ahorrar dinero", g: 3, lv: "N4" },
  { k: "通勤する", f: "つうきんする", m: "Ir al trabajo", g: 3, lv: "N4" },
  { k: "通知する", f: "つうちする", m: "Notificar", g: 3, lv: "N4" },
  { k: "通学する", f: "つうがくする", m: "Ir a la escuela", g: 3, lv: "N4" },
  { k: "停電する", f: "ていでんする", m: "Haber un corte de luz", g: 3, lv: "N4" },
  { k: "テストする", f: "てすとする", m: "Hacer un test", g: 3, lv: "N4" },
  { k: "返事する", f: "へんじする", m: "Responder / Contestar", g: 3, lv: "N4" },
  { k: "放送する", f: "ほうそうする", m: "Transmitir / Emitir", g: 3, lv: "N4" },
  { k: "翻訳する", f: "ほんやくする", m: "Traducir (escrito)", g: 3, lv: "N4" },
  { k: "約束する", f: "やくそくする", m: "Prometer", g: 3, lv: "N4" },
  { k: "予習する", f: "よしゅうする", m: "Preparar la lección", g: 3, lv: "N4" },
  { k: "予約する", f: "よやくする", m: "Reservar", g: 3, lv: "N4" },
  { k: "利用する", f: "りようする", m: "Utilizar / Aprovechar", g: 3, lv: "N4" },
  { k: "留学する", f: "りゅうがくする", m: "Estudiar en el extranjero", g: 3, lv: "N4" },
  { k: "練習する", f: "れんしゅうする", m: "Practicar", g: 3, lv: "N4" },
  { k: "連絡する", f: "れんらくする", m: "Contactar", g: 3, lv: "N4" },
  { k: "合格する", f: "ごうかくする", m: "Aprobar (un examen)", g: 3, lv: "N4" },
  { k: "復習する", f: "ふくしゅうする", m: "Repasar", g: 3, lv: "N4" },
  { k: "見学する", f: "けんがくする", m: "Visitar para aprender", g: 3, lv: "N4" },
  { k: "経験する", f: "けいけんする", m: "Experimentar", g: 3, lv: "N4" },
  { k: "計画する", f: "けいかくする", m: "Planear", g: 3, lv: "N4" },
  { k: "喧嘩する", f: "けんかする", m: "Pelear", g: 3, lv: "N4" },
  { k: "散歩する", f: "さんぽする", m: "Pasear", g: 3, lv: "N4" },
  { k: "出席する", f: "しゅっせきする", m: "Asistir", g: 3, lv: "N4" },
  { k: "出発する", f: "しゅっぱつする", m: "Partir / Salir (viaje)", g: 3, lv: "N4" },
  { k: "準備する", f: "じゅんびする", m: "Preparar", g: 3, lv: "N4" },
  { k: "質問する", f: "しつもんする", m: "Preguntar", g: 3, lv: "N4" },
  { k: "掃除する", f: "そうじする", m: "Limpiar", g: 3, lv: "N4" },
  { k: "洗濯する", f: "せんたくする", m: "Lavar la ropa", g: 3, lv: "N4" },
  { k: "到着する", f: "とうちゃくする", m: "Llegar", g: 3, lv: "N4" }

];

const grammarData = [

  // =========================
  // N4
  // =========================

  { f: "nai_stem", tag: "〜なければなりません", m: "Tener que (Obligación)", lv: "N4", formula: "V-nai (sin i) + ければなりません" },
  { f: "nai_stem", tag: "〜なくてもいいです", m: "No es necesario", lv: "N4", formula: "V-nai (sin i) + くてもいいです" },
  { f: "te", tag: "〜てはいけません", m: "Prohibido / No se permite", lv: "N4", formula: "V-te + はいけません" },
  { f: "te", tag: "〜てもいいです", m: "Se permite / Está bien si...", lv: "N4", formula: "V-te + もいいです" },

  // Intención y Planes
  { f: "dic", tag: "〜つもりです", m: "Tener la intención de", lv: "N4", formula: "V-dic / V-nai + つもりです" },
  { f: "dic", tag: "〜予定です", m: "Estar planeado que", lv: "N4", formula: "V-dic / Sustantivo + の + 予定です" },
  { f: "volitivo", tag: "〜（よ）うと思っています", m: "Estoy pensando en (intención)", lv: "N4", formula: "V-volitivo + と思っています" },

  // Estados y Acciones Terminadas
  { f: "te", tag: "〜ています", m: "Estar haciendo / Estado resultante", lv: "N4", formula: "V-te + います" },
  { f: "te", tag: "〜てあります", m: "Estar hecho (con intención)", lv: "N4", formula: "V-te + あります" },
  { f: "te", tag: "〜ておきます", m: "Hacer algo con antelación", lv: "N4", formula: "V-te + おきます" },
  { f: "te", tag: "〜てしまいます", m: "Hacer algo por completo / Lamentablemente", lv: "N4", formula: "V-te + しまいます" },

  // Experiencia e Intentos
  { f: "ta", tag: "〜たことがあります", m: "Haber tenido la experiencia de", lv: "N4", formula: "V-ta + ことがあります" },
  { f: "te", tag: "〜てみます", m: "Intentar hacer algo (ver qué pasa)", lv: "N4", formula: "V-te + みます" },

  // Recomendaciones y Opiniones
  { f: "ta", tag: "〜たほうがいいです", m: "Es mejor que... (recomendación)", lv: "N4", formula: "V-ta + ほうがいいです" },
  { f: "nai", tag: "〜ないほうがいいです", m: "Es mejor que no...", lv: "N4", formula: "V-nai + ほうがいいです" },
  { f: "plain", tag: "〜と思います", m: "Creo que...", lv: "N4", formula: "Forma Plana + と思います" },
  { f: "plain", tag: "〜と言っていました", m: "Dijo que...", lv: "N4", formula: "Forma Plana + と言っていました" },

  // Deseos
  { f: "masu", tag: "〜たいです", m: "Querer hacer algo", lv: "N4", formula: "V-masu (sin masu) + たいです" },
  { f: "dic", tag: "〜たがっています", m: "Alguien más quiere hacer algo", lv: "N4", formula: "V-masu + たがっています" },
  { f: "sustantivo", tag: "〜がほしいです", m: "Querer algo (objeto)", lv: "N4", formula: "Sustantivo + がほしいです" },


// Habilidad y Capacidad (Potencial)
  { f: "potencial", tag: "〜（え）る", m: "Poder hacer algo", lv: "N4", formula: "V-potencial + ます" },
  { f: "dic", tag: "〜ことができる", m: "Ser capaz de", lv: "N4", formula: "V-dic + ことが出来る" },

  // Condicionales (Si...)
  { f: "ta", tag: "〜たら", m: "Si / Cuando ocurre algo", lv: "N4", formula: "V-ta + ら" },
  { f: "ba", tag: "〜ば", m: "Si... (condición necesaria)", lv: "N4", formula: "V-condicional (forma ba)" },
  { f: "dic", tag: "〜と", m: "Si... (resultado natural/fijo)", lv: "N4", formula: "V-dic + と" },

  // Dar y Recibir (Favor y Cortesía)
  { f: "te", tag: "〜てあげる", m: "Hacer un favor a alguien", lv: "N4", formula: "V-te + あげる" },
  { f: "te", tag: "〜てくれる", m: "Alguien me hace un favor", lv: "N4", formula: "V-te + くれる" },
  { f: "te", tag: "〜てもらう", m: "Recibir un favor de alguien", lv: "N4", formula: "V-te + もらう" },
  { f: "te", tag: "〜ていただけませんか", m: "¿Podría hacerme el favor de...?", lv: "N4", formula: "V-te + いただけませんか" },

  // Probabilidad y Apariencia
  { f: "plain", tag: "〜でしょう", m: "Probablemente / ¿Verdad?", lv: "N4", formula: "Forma Plana + でしょう" },
  { f: "plain", tag: "〜かもしれません", m: "Quizás / Tal vez", lv: "N4", formula: "Forma Plana + かもしれません" },
  { f: "masu", tag: "〜そうです", m: "Parece que... (apariencia)", lv: "N4", formula: "V-masu / Adj-i (sin i) + そうです" },
  { f: "plain", tag: "〜そうです", m: "He oído que...", lv: "N4", formula: "Forma Plana + そうです" },
  { f: "plain", tag: "〜はずです", m: "Se supone que / Debería ser", lv: "N4", formula: "Forma Plana + はずです" },

  // Razones y Causas
  { f: "plain", tag: "〜ので", m: "Porque / Debido a que (formal)", lv: "N4", formula: "Forma Plana + ので" },
  { f: "plain", tag: "〜し、〜し", m: "Además de... y...", lv: "N4", formula: "Frase 1 + し + Frase 2 + し" },
  { f: "te", tag: "〜て、〜", m: "Hacer esto y luego...", lv: "N4", formula: "V-te + Frase consecutiva" },

  // Cambios de Estado
  { f: "dic", tag: "〜ようになる", m: "Empezar a ser capaz de / Llegar a", lv: "N4", formula: "V-dic + ようになる" },
  { f: "dic", tag: "〜ようにする", m: "Intentar / Asegurarse de", lv: "N4", formula: "V-dic + ようにする" },
  { f: "adjetivo", tag: "〜くなる / 〜になる", m: "Volverse / Convertirse en", lv: "N4", formula: "Adj-i -> くなる / Adj-na -> になる" },


// Voz Pasiva y Causativa (Dificultad Alta N4)
  { f: "passive", tag: "〜られる", m: "Ser hecho por (Voz Pasiva)", lv: "N4", formula: "V-pasivo + ます" },
  { f: "causative", tag: "〜させる", m: "Hacer / Dejar que alguien haga", lv: "N4", formula: "V-causativo + ます" },
  { f: "causative_passive", tag: "〜させられる", m: "Ser obligado a hacer algo", lv: "N4", formula: "V-causativo pasivo" },

  // Propósito y Finalidad
  { f: "dic", tag: "〜ために", m: "Para / Con el fin de", lv: "N4", formula: "V-dic / Sustantivo + の + ために" },
  { f: "dic", tag: "〜ように", m: "De modo que / Para que", lv: "N4", formula: "V-dic / V-nai + ように" },
  { f: "masu", tag: "〜に行く / 来る", m: "Ir / Venir a hacer algo", lv: "N4", formula: "V-masu (sin masu) + に + 行く/来る" },

  // Tiempo y Secuencia
  { f: "plain", tag: "〜時", m: "Cuando...", lv: "N4", formula: "Forma Plana + 時（とき）" },
  { f: "dic", tag: "〜まえに", m: "Antes de...", lv: "N4", formula: "V-dic + まえに" },
  { f: "ta", tag: "〜たあとで", m: "Después de...", lv: "N4", formula: "V-ta + あとで" },
  { f: "te", tag: "〜てから", m: "Desde que hice / Después de", lv: "N4", formula: "V-te + から" },
  { f: "dic", tag: "〜うちに", m: "Mientras / Antes de que cambie el estado", lv: "N4", formula: "V-dic / V-nai / Adj / Sust + の + うちに" },

  // Simultaneidad y Manera
  { f: "masu", tag: "〜ながら", m: "Hacer algo mientras se hace otra cosa", lv: "N4", formula: "V-masu + ながら" },
  { f: "masu", tag: "〜方", m: "Manera de hacer algo", lv: "N4", formula: "V-masu + 方（かた）" },
  { f: "masu", tag: "〜すぎる", m: "Hacer algo en exceso", lv: "N4", formula: "V-masu / Adj + すぎる" },
  { f: "masu", tag: "〜やすい", m: "Fácil de hacer", lv: "N4", formula: "V-masu + やすい" },
  { f: "masu", tag: "〜にくい", m: "Difícil de hacer", lv: "N4", formula: "V-masu + にくい" },

  // Comparaciones
  { f: "sustantivo", tag: "〜より〜ほうが", m: "Más que... es mejor...", lv: "N4", formula: "A より B のほうが Adj" },
  { f: "sustantivo", tag: "〜ほど〜ない", m: "No tan... como...", lv: "N4", formula: "A は B ほど Adj-nai" },

  // Sustantivación y Otros
  { f: "plain", tag: "〜の", m: "El hecho de (Sustantivador)", lv: "N4", formula: "Forma Plana + の" },
  { f: "plain", tag: "〜こと", m: "Cosa / El hecho de (Sustantivador)", lv: "N4", formula: "Forma Plana + こと" },


  { f: "plain", tag: "〜ようです", m: "Parece que... (conjetura propia)", lv: "N4", formula: "Forma Plana / [Sust + の] + ようです" },
  { f: "plain", tag: "〜みたいです", m: "Parece... / Es como... (coloquial)", lv: "N4", formula: "Sustantivo / Forma Plana + みたいです" },
  { f: "plain", tag: "〜らしいです", m: "Parece que / Típico de...", lv: "N4", formula: "Sustantivo / Forma Plana + らしいです" },

  // Duda y Preguntas Indirectas
  { f: "plain", tag: "〜かどうか", m: "Si... o no", lv: "N4", formula: "Forma Plana (sin da) + かどうか" },
  { f: "plain", tag: "〜か", m: "Pregunta indirecta (quién, qué, etc.)", lv: "N4", formula: "Pronombre interrogativo + Forma Plana + か" },

  // Partículas Compuestas e Intermedias
  { f: "sustantivo", tag: "〜について", m: "Sobre / Acerca de", lv: "N4", formula: "Sustantivo + について" },
  { f: "sustantivo", tag: "〜によって", m: "Por (agente en pasiva) / Debido a", lv: "N4", formula: "Sustantivo + によって" },
  { f: "dic", tag: "〜のに", m: "A pesar de / Aunque...", lv: "N4", formula: "Forma Plana + のに" },
  { f: "dic", tag: "〜のに", m: "Para... (uso o propósito de un objeto)", lv: "N4", formula: "V-dic + のに + [Uso/Gasto/Tiempo]" },

  // Limitación y Énfasis
  { f: "sustantivo", tag: "〜しか〜ない", m: "Solo / Nada más que... (negativo)", lv: "N4", formula: "Sustantivo + しか + V-nai" },
  { f: "sustantivo", tag: "〜ばかり", m: "Solo / Nada más que...", lv: "N4", formula: "Sustantivo / V-te + ばかり" },
  { f: "ta", tag: "〜たばかり", m: "Acabar de hacer algo", lv: "N4", formula: "V-ta + ばかり" },
  { f: "dic", tag: "〜ところです", m: "Estar a punto de / Estar haciendo / Acabar de", lv: "N4", formula: "V-dic / V-te iru / V-ta + ところです" },

  // Facilitadores de Comunicación
  { f: "plain", tag: "〜んです / 〜のだ", m: "Es que... (explicación)", lv: "N4", formula: "Forma Plana + んです" },
  { f: "sustantivo", tag: "〜など", m: "Etcétera / Cosas como...", lv: "N4", formula: "Sustantivo + など" },
  { f: "plain", tag: "〜なら", m: "Si es el caso de... / Si se trata de...", lv: "N4", formula: "Sustantivo / Forma Plana + なら" },

  // Adverbios y otros
  { f: "plain", tag: "〜が決まる", m: "Se decide que...", lv: "N4", formula: "V-dic + ことに + なります / きまります" },
  { f: "plain", tag: "〜にする", m: "Decidir hacer...", lv: "N4", formula: "V-dic + ことに + します" }

  // Lenguaje Honorífico (Sonkeigo - Elevando al otro)
  { f: "honorific", tag: "お〜になります", m: "Hacer algo (Honorífico)", lv: "N4", formula: "お + V-masu (stem) + になります" },
  { f: "honorific", tag: "〜られます", m: "Hacer algo (Honorífico simple)", lv: "N4", formula: "V-pasivo utilizado como honorífico" },
  { f: "honorific", tag: "ください", m: "Por favor haga (Honorífico)", lv: "N4", formula: "お + V-masu (stem) + ください" },

  // Lenguaje Humilde (Kenjougo - Bajándose uno mismo)
  { f: "humble", tag: "お〜します", m: "Hacer algo (Humilde)", lv: "N4", formula: "お + V-masu (stem) + します" },
  { f: "humble", tag: "〜ていただく", m: "Recibir la acción de un superior", lv: "N4", formula: "V-te + いただく" },

  // Expresiones de "Dar y Recibir" de Respeto
  { f: "te", tag: "〜てくださる", m: "Alguien superior me hace un favor", lv: "N4", formula: "V-te + くださる" },
  { f: "te", tag: "〜て差し上げる", m: "Hacer un favor a un superior", lv: "N4", formula: "V-te + 差し上げる" },

  // Estructuras del Minna no Nihongo (Cap. 26-50)
  { f: "masu", tag: "〜すぎる", m: "Demasiado / En exceso", lv: "N4", formula: "V-masu / Adj + すぎる" },
  { f: "masu", tag: "〜だす", m: "Empezar a (repentinamente)", lv: "N4", formula: "V-masu + だす" },
  { f: "masu", tag: "〜おわる", m: "Terminar de hacer", lv: "N4", formula: "V-masu + おわる" },
  { f: "plain", tag: "〜し", m: "No solo... sino también (enlistar razones)", lv: "N4", formula: "Forma Plana + し" },
  { f: "plain", tag: "〜はずだ", m: "Debería ser que / Se espera que", lv: "N4", formula: "Forma Plana + はずだ" },
  { f: "plain", tag: "〜はずがない", m: "Es imposible que...", lv: "N4", formula: "Forma Plana + はずがない" },
  { f: "te", tag: "〜てくる", m: "Acción que viene hacia el presente / Comienza a", lv: "N4", formula: "V-te + くる" },
  { f: "te", tag: "〜ていく", m: "Acción que se aleja hacia el futuro / Continúa", lv: "N4", formula: "V-te + いく" },
  { f: "plain", tag: "〜おそれがある", m: "Existe el riesgo de que...", lv: "N4", formula: "V-dic / Sust + の + おそれがある" },

  // Adverbios que cambian la gramática
  { f: "adv", tag: "なかなか〜ない", m: "No lograr hacer algo (pese al esfuerzo)", lv: "N4", formula: "なかなか + V-nai" },
  { f: "adv", tag: "ぜったいに〜ない", m: "Absolutamente no / Jamás", lv: "N4", formula: "ぜったいに + V-nai" },
  { f: "adv", tag: "けっして〜ない", m: "Nunca / De ninguna manera", lv: "N4", formula: "けっして + V-nai" },
  { f: "adv", tag: "たぶん〜だろう", m: "Probablemente...", lv: "N4", formula: "たぶん + Forma Plana + だろう" }

];